// The tools service's contract: what its runner accepts and answers.
// Another service depends on this package, never on the service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: guide/proto/tools/v1/tools.proto

package toolsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Run asks for one call of a tool. It is a call, answered with Ran, and its
// deadline is the tool's.
type Run struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tool's name: calc, sleep.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// What it is given, as the model wrote it.
	Args          string `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_guide_proto_tools_v1_tools_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_tools_v1_tools_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_guide_proto_tools_v1_tools_proto_rawDescGZIP(), []int{0}
}

func (x *Run) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Run) GetArgs() string {
	if x != nil {
		return x.Args
	}
	return ""
}

// Ran is the runner's answer: what the tool returned, or why it did not. A
// tool that fails, crashes or is not there is part of the answer; an error
// means the runner did not answer.
type Ran struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Output string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// Why there is no output. Empty when there is.
	Failed        string `protobuf:"bytes,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ran) Reset() {
	*x = Ran{}
	mi := &file_guide_proto_tools_v1_tools_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ran) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ran) ProtoMessage() {}

func (x *Ran) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_tools_v1_tools_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ran.ProtoReflect.Descriptor instead.
func (*Ran) Descriptor() ([]byte, []int) {
	return file_guide_proto_tools_v1_tools_proto_rawDescGZIP(), []int{1}
}

func (x *Ran) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *Ran) GetFailed() string {
	if x != nil {
		return x.Failed
	}
	return ""
}

var File_guide_proto_tools_v1_tools_proto protoreflect.FileDescriptor

const file_guide_proto_tools_v1_tools_proto_rawDesc = "" +
	"\n" +
	" guide/proto/tools/v1/tools.proto\x12\btools.v1\"-\n" +
	"\x03Run\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04args\x18\x02 \x01(\tR\x04args\"5\n" +
	"\x03Ran\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\tR\x06failedBEZCgithub.com/floatdrop/grpcproc/examples/guide/proto/tools/v1;toolsv1b\x06proto3"

var (
	file_guide_proto_tools_v1_tools_proto_rawDescOnce sync.Once
	file_guide_proto_tools_v1_tools_proto_rawDescData []byte
)

func file_guide_proto_tools_v1_tools_proto_rawDescGZIP() []byte {
	file_guide_proto_tools_v1_tools_proto_rawDescOnce.Do(func() {
		file_guide_proto_tools_v1_tools_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guide_proto_tools_v1_tools_proto_rawDesc), len(file_guide_proto_tools_v1_tools_proto_rawDesc)))
	})
	return file_guide_proto_tools_v1_tools_proto_rawDescData
}

var file_guide_proto_tools_v1_tools_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_guide_proto_tools_v1_tools_proto_goTypes = []any{
	(*Run)(nil), // 0: tools.v1.Run
	(*Ran)(nil), // 1: tools.v1.Ran
}
var file_guide_proto_tools_v1_tools_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_guide_proto_tools_v1_tools_proto_init() }
func file_guide_proto_tools_v1_tools_proto_init() {
	if File_guide_proto_tools_v1_tools_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guide_proto_tools_v1_tools_proto_rawDesc), len(file_guide_proto_tools_v1_tools_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guide_proto_tools_v1_tools_proto_goTypes,
		DependencyIndexes: file_guide_proto_tools_v1_tools_proto_depIdxs,
		MessageInfos:      file_guide_proto_tools_v1_tools_proto_msgTypes,
	}.Build()
	File_guide_proto_tools_v1_tools_proto = out.File
	file_guide_proto_tools_v1_tools_proto_goTypes = nil
	file_guide_proto_tools_v1_tools_proto_depIdxs = nil
}
