// grpcproc.inspect.v1 is the inspection surface of a grpcproc node: what
// processes exist, what is in their mailboxes, what each says about itself,
// what is happening on its links. Every tool (CLI, UI, MCP server) is a
// client of this service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grpcproc/inspect/v1/inspect.proto

package inspectv1

import (
	v1 "github.com/floatdrop/grpcproc/proto/grpcproc/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkState int32

const (
	LinkState_LINK_STATE_UNSPECIFIED LinkState = 0
	LinkState_LINK_STATE_CONNECTING  LinkState = 1
	LinkState_LINK_STATE_UP          LinkState = 2
	LinkState_LINK_STATE_DOWN        LinkState = 3
)

// Enum value maps for LinkState.
var (
	LinkState_name = map[int32]string{
		0: "LINK_STATE_UNSPECIFIED",
		1: "LINK_STATE_CONNECTING",
		2: "LINK_STATE_UP",
		3: "LINK_STATE_DOWN",
	}
	LinkState_value = map[string]int32{
		"LINK_STATE_UNSPECIFIED": 0,
		"LINK_STATE_CONNECTING":  1,
		"LINK_STATE_UP":          2,
		"LINK_STATE_DOWN":        3,
	}
)

func (x LinkState) Enum() *LinkState {
	p := new(LinkState)
	*p = x
	return p
}

func (x LinkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkState) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcproc_inspect_v1_inspect_proto_enumTypes[0].Descriptor()
}

func (LinkState) Type() protoreflect.EnumType {
	return &file_grpcproc_inspect_v1_inspect_proto_enumTypes[0]
}

func (x LinkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkState.Descriptor instead.
func (LinkState) EnumDescriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{0}
}

type ProcessState int32

const (
	ProcessState_PROCESS_STATE_UNSPECIFIED   ProcessState = 0
	ProcessState_PROCESS_STATE_IDLE          ProcessState = 1
	ProcessState_PROCESS_STATE_RUNNING       ProcessState = 2
	ProcessState_PROCESS_STATE_WAITING_REPLY ProcessState = 3
	ProcessState_PROCESS_STATE_EXITING       ProcessState = 4
)

// Enum value maps for ProcessState.
var (
	ProcessState_name = map[int32]string{
		0: "PROCESS_STATE_UNSPECIFIED",
		1: "PROCESS_STATE_IDLE",
		2: "PROCESS_STATE_RUNNING",
		3: "PROCESS_STATE_WAITING_REPLY",
		4: "PROCESS_STATE_EXITING",
	}
	ProcessState_value = map[string]int32{
		"PROCESS_STATE_UNSPECIFIED":   0,
		"PROCESS_STATE_IDLE":          1,
		"PROCESS_STATE_RUNNING":       2,
		"PROCESS_STATE_WAITING_REPLY": 3,
		"PROCESS_STATE_EXITING":       4,
	}
)

func (x ProcessState) Enum() *ProcessState {
	p := new(ProcessState)
	*p = x
	return p
}

func (x ProcessState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProcessState) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcproc_inspect_v1_inspect_proto_enumTypes[1].Descriptor()
}

func (ProcessState) Type() protoreflect.EnumType {
	return &file_grpcproc_inspect_v1_inspect_proto_enumTypes[1]
}

func (x ProcessState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProcessState.Descriptor instead.
func (ProcessState) EnumDescriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{1}
}

type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Incarnation   uint64                 `protobuf:"varint,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{0}
}

func (x *NodeID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeID) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *NodeID                `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Outbound      bool                   `protobuf:"varint,2,opt,name=outbound,proto3" json:"outbound,omitempty"`
	State         LinkState              `protobuf:"varint,3,opt,name=state,proto3,enum=grpcproc.inspect.v1.LinkState" json:"state,omitempty"`
	EstablishedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=established_at,json=establishedAt,proto3" json:"established_at,omitempty"`
	Reconnects    uint64                 `protobuf:"varint,5,opt,name=reconnects,proto3" json:"reconnects,omitempty"`
	Messages      uint64                 `protobuf:"varint,6,opt,name=messages,proto3" json:"messages,omitempty"`
	Bytes         uint64                 `protobuf:"varint,7,opt,name=bytes,proto3" json:"bytes,omitempty"`
	LastError     string                 `protobuf:"bytes,8,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// Set on an outbound link that is down because dials to the peer failed:
	// sends to it fail at once until then (Config.DialBackoff).
	RetryAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=retry_at,json=retryAt,proto3" json:"retry_at,omitempty"`
	// Outbound: envelopes waiting to be written.
	Queued uint32 `protobuf:"varint,10,opt,name=queued,proto3" json:"queued,omitempty"`
	// Outbound: the bytes of their message bodies.
	QueuedBytes uint64 `protobuf:"varint,11,opt,name=queued_bytes,json=queuedBytes,proto3" json:"queued_bytes,omitempty"`
	// How many sessions with the peer have ended: links lost, or the peer
	// reporting it ended one.
	Sessions      uint64 `protobuf:"varint,12,opt,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{1}
}

func (x *Link) GetPeer() *NodeID {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *Link) GetOutbound() bool {
	if x != nil {
		return x.Outbound
	}
	return false
}

func (x *Link) GetState() LinkState {
	if x != nil {
		return x.State
	}
	return LinkState_LINK_STATE_UNSPECIFIED
}

func (x *Link) GetEstablishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EstablishedAt
	}
	return nil
}

func (x *Link) GetReconnects() uint64 {
	if x != nil {
		return x.Reconnects
	}
	return 0
}

func (x *Link) GetMessages() uint64 {
	if x != nil {
		return x.Messages
	}
	return 0
}

func (x *Link) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Link) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Link) GetRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RetryAt
	}
	return nil
}

func (x *Link) GetQueued() uint32 {
	if x != nil {
		return x.Queued
	}
	return 0
}

func (x *Link) GetQueuedBytes() uint64 {
	if x != nil {
		return x.QueuedBytes
	}
	return 0
}

func (x *Link) GetSessions() uint64 {
	if x != nil {
		return x.Sessions
	}
	return 0
}

type NodeInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          *NodeID                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Advertise   string                 `protobuf:"bytes,2,opt,name=advertise,proto3" json:"advertise,omitempty"`
	StartedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Processes   uint32                 `protobuf:"varint,4,opt,name=processes,proto3" json:"processes,omitempty"`
	Spawned     uint64                 `protobuf:"varint,5,opt,name=spawned,proto3" json:"spawned,omitempty"`
	Exited      uint64                 `protobuf:"varint,6,opt,name=exited,proto3" json:"exited,omitempty"`
	DeadLetters uint64                 `protobuf:"varint,7,opt,name=dead_letters,json=deadLetters,proto3" json:"dead_letters,omitempty"`
	Links       []*Link                `protobuf:"bytes,8,rep,name=links,proto3" json:"links,omitempty"`
	// The node's Config.Metadata: its version, its zone.
	Metadata map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// What the node's Config.Membership reports up, by name (Node.Members):
	// the node among them once it reports it; none without a Membership. A
	// member whose name, address or metadata could not be a node's own (not
	// valid UTF-8, or over 16 KiB) is left out.
	Members       []*Member `protobuf:"bytes,10,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetId() *NodeID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *NodeInfo) GetAdvertise() string {
	if x != nil {
		return x.Advertise
	}
	return ""
}

func (x *NodeInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *NodeInfo) GetProcesses() uint32 {
	if x != nil {
		return x.Processes
	}
	return 0
}

func (x *NodeInfo) GetSpawned() uint64 {
	if x != nil {
		return x.Spawned
	}
	return 0
}

func (x *NodeInfo) GetExited() uint64 {
	if x != nil {
		return x.Exited
	}
	return 0
}

func (x *NodeInfo) GetDeadLetters() uint64 {
	if x != nil {
		return x.DeadLetters
	}
	return 0
}

func (x *NodeInfo) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *NodeInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *NodeInfo) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

// A node that Membership reports up.
type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The incarnation is 0 when the Membership does not know it.
	Id *NodeID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Where peers dial it: its Config.Advertise.
	Addr          string            `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Metadata      map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{3}
}

func (x *Member) GetId() *NodeID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Member) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Member) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Mailbox struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Depth     uint32                 `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Peak      uint32                 `protobuf:"varint,2,opt,name=peak,proto3" json:"peak,omitempty"`
	OldestAge *durationpb.Duration   `protobuf:"bytes,3,opt,name=oldest_age,json=oldestAge,proto3" json:"oldest_age,omitempty"`
	// What WithMailboxLimit bounds it to; 0 is no bound.
	Limit         uint32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mailbox) Reset() {
	*x = Mailbox{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mailbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mailbox) ProtoMessage() {}

func (x *Mailbox) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mailbox.ProtoReflect.Descriptor instead.
func (*Mailbox) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{4}
}

func (x *Mailbox) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Mailbox) GetPeak() uint32 {
	if x != nil {
		return x.Peak
	}
	return 0
}

func (x *Mailbox) GetOldestAge() *durationpb.Duration {
	if x != nil {
		return x.OldestAge
	}
	return nil
}

func (x *Mailbox) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ProcessInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pid   *v1.PID                `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	// Registered with WithName; empty for an unnamed process.
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Parent        *v1.PID                `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty"`
	State         ProcessState           `protobuf:"varint,6,opt,name=state,proto3,enum=grpcproc.inspect.v1.ProcessState" json:"state,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Mailbox       *Mailbox               `protobuf:"bytes,8,opt,name=mailbox,proto3" json:"mailbox,omitempty"`
	Received      uint64                 `protobuf:"varint,9,opt,name=received,proto3" json:"received,omitempty"`
	Sent          uint64                 `protobuf:"varint,10,opt,name=sent,proto3" json:"sent,omitempty"`
	CallsInFlight uint32                 `protobuf:"varint,11,opt,name=calls_in_flight,json=callsInFlight,proto3" json:"calls_in_flight,omitempty"`
	LastMessage   string                 `protobuf:"bytes,12,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	Monitors      uint32                 `protobuf:"varint,13,opt,name=monitors,proto3" json:"monitors,omitempty"`
	// Processes monitoring or linked to this one.
	Watchers uint32 `protobuf:"varint,14,opt,name=watchers,proto3" json:"watchers,omitempty"`
	Wakeups  uint64 `protobuf:"varint,15,opt,name=wakeups,proto3" json:"wakeups,omitempty"`
	// slog.Level: -4 debug, 0 info, 4 warn, 8 error.
	LogLevel int32 `protobuf:"zigzag32,16,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	// Process links this one holds: whose exits end it, or reach it as an
	// Exited message. Not links to nodes.
	Links uint32 `protobuf:"varint,17,opt,name=links,proto3" json:"links,omitempty"`
	// Whether the exits of processes it is linked to reach it as messages.
	TrapExit bool `protobuf:"varint,18,opt,name=trap_exit,json=trapExit,proto3" json:"trap_exit,omitempty"`
	// The global names it holds (Process.Claim), ordered.
	Globals       []string `protobuf:"bytes,19,rep,name=globals,proto3" json:"globals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInfo) Reset() {
	*x = ProcessInfo{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInfo) ProtoMessage() {}

func (x *ProcessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInfo.ProtoReflect.Descriptor instead.
func (*ProcessInfo) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessInfo) GetPid() *v1.PID {
	if x != nil {
		return x.Pid
	}
	return nil
}

func (x *ProcessInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProcessInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ProcessInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ProcessInfo) GetParent() *v1.PID {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *ProcessInfo) GetState() ProcessState {
	if x != nil {
		return x.State
	}
	return ProcessState_PROCESS_STATE_UNSPECIFIED
}

func (x *ProcessInfo) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *ProcessInfo) GetMailbox() *Mailbox {
	if x != nil {
		return x.Mailbox
	}
	return nil
}

func (x *ProcessInfo) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *ProcessInfo) GetSent() uint64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *ProcessInfo) GetCallsInFlight() uint32 {
	if x != nil {
		return x.CallsInFlight
	}
	return 0
}

func (x *ProcessInfo) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *ProcessInfo) GetMonitors() uint32 {
	if x != nil {
		return x.Monitors
	}
	return 0
}

func (x *ProcessInfo) GetWatchers() uint32 {
	if x != nil {
		return x.Watchers
	}
	return 0
}

func (x *ProcessInfo) GetWakeups() uint64 {
	if x != nil {
		return x.Wakeups
	}
	return 0
}

func (x *ProcessInfo) GetLogLevel() int32 {
	if x != nil {
		return x.LogLevel
	}
	return 0
}

func (x *ProcessInfo) GetLinks() uint32 {
	if x != nil {
		return x.Links
	}
	return 0
}

func (x *ProcessInfo) GetTrapExit() bool {
	if x != nil {
		return x.TrapExit
	}
	return false
}

func (x *ProcessInfo) GetGlobals() []string {
	if x != nil {
		return x.Globals
	}
	return nil
}

// Target names a process by pid or by name, on the request's node.
type Target struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Target_Pid
	//	*Target_Name
	Kind          isTarget_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{6}
}

func (x *Target) GetKind() isTarget_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Target) GetPid() *v1.PID {
	if x != nil {
		if x, ok := x.Kind.(*Target_Pid); ok {
			return x.Pid
		}
	}
	return nil
}

func (x *Target) GetName() string {
	if x != nil {
		if x, ok := x.Kind.(*Target_Name); ok {
			return x.Name
		}
	}
	return ""
}

type isTarget_Kind interface {
	isTarget_Kind()
}

type Target_Pid struct {
	Pid *v1.PID `protobuf:"bytes,1,opt,name=pid,proto3,oneof"`
}

type Target_Name struct {
	Name string `protobuf:"bytes,2,opt,name=name,proto3,oneof"`
}

func (*Target_Pid) isTarget_Kind() {}

func (*Target_Name) isTarget_Kind() {}

type LookupNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupNameRequest) Reset() {
	*x = LookupNameRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupNameRequest) ProtoMessage() {}

func (x *LookupNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupNameRequest.ProtoReflect.Descriptor instead.
func (*LookupNameRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{7}
}

func (x *LookupNameRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *LookupNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Pid           *v1.PID                `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupNameResponse) Reset() {
	*x = LookupNameResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupNameResponse) ProtoMessage() {}

func (x *LookupNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupNameResponse.ProtoReflect.Descriptor instead.
func (*LookupNameResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{8}
}

func (x *LookupNameResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *LookupNameResponse) GetPid() *v1.PID {
	if x != nil {
		return x.Pid
	}
	return nil
}

type ListNamesRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Node   string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Prefix string                 `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// At most this many, ordered by name; 0 is 1000.
	Limit         uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamesRequest) Reset() {
	*x = ListNamesRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamesRequest) ProtoMessage() {}

func (x *ListNamesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamesRequest.ProtoReflect.Descriptor instead.
func (*ListNamesRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{9}
}

func (x *ListNamesRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ListNamesRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *ListNamesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GlobalName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pid           *v1.PID                `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalName) Reset() {
	*x = GlobalName{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalName) ProtoMessage() {}

func (x *GlobalName) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalName.ProtoReflect.Descriptor instead.
func (*GlobalName) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{10}
}

func (x *GlobalName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GlobalName) GetPid() *v1.PID {
	if x != nil {
		return x.Pid
	}
	return nil
}

type ListNamesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         []*GlobalName          `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNamesResponse) Reset() {
	*x = ListNamesResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNamesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNamesResponse) ProtoMessage() {}

func (x *ListNamesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNamesResponse.ProtoReflect.Descriptor instead.
func (*ListNamesResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{11}
}

func (x *ListNamesResponse) GetNames() []*GlobalName {
	if x != nil {
		return x.Names
	}
	return nil
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{12}
}

func (x *GetNodeRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeInfo              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{13}
}

func (x *GetNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

// ListProcessesRequest filters are ANDed; empty fields match everything.
type ListProcessesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Node  string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// Substring of the process's name; a process with none matches only an
	// empty filter.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Exact label.
	Label string       `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	State ProcessState `protobuf:"varint,4,opt,name=state,proto3,enum=grpcproc.inspect.v1.ProcessState" json:"state,omitempty"`
	// Only processes whose mailbox holds at least this many messages.
	MinMailbox    uint32 `protobuf:"varint,5,opt,name=min_mailbox,json=minMailbox,proto3" json:"min_mailbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesRequest) Reset() {
	*x = ListProcessesRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesRequest) ProtoMessage() {}

func (x *ListProcessesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesRequest.ProtoReflect.Descriptor instead.
func (*ListProcessesRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{14}
}

func (x *ListProcessesRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ListProcessesRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListProcessesRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ListProcessesRequest) GetState() ProcessState {
	if x != nil {
		return x.State
	}
	return ProcessState_PROCESS_STATE_UNSPECIFIED
}

func (x *ListProcessesRequest) GetMinMailbox() uint32 {
	if x != nil {
		return x.MinMailbox
	}
	return 0
}

type ListProcessesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Processes     []*ProcessInfo         `protobuf:"bytes,1,rep,name=processes,proto3" json:"processes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProcessesResponse) Reset() {
	*x = ListProcessesResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProcessesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProcessesResponse) ProtoMessage() {}

func (x *ListProcessesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProcessesResponse.ProtoReflect.Descriptor instead.
func (*ListProcessesResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{15}
}

func (x *ListProcessesResponse) GetProcesses() []*ProcessInfo {
	if x != nil {
		return x.Processes
	}
	return nil
}

type GetProcessRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Node   string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Target *Target                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Ask the process what it believes (WithInspect).
	Inspect bool `protobuf:"varint,3,opt,name=inspect,proto3" json:"inspect,omitempty"`
	// How long to wait for a busy process to answer. Default 1s.
	InspectTimeout *durationpb.Duration `protobuf:"bytes,4,opt,name=inspect_timeout,json=inspectTimeout,proto3" json:"inspect_timeout,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProcessRequest) Reset() {
	*x = GetProcessRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessRequest) ProtoMessage() {}

func (x *GetProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessRequest.ProtoReflect.Descriptor instead.
func (*GetProcessRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{16}
}

func (x *GetProcessRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *GetProcessRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *GetProcessRequest) GetInspect() bool {
	if x != nil {
		return x.Inspect
	}
	return false
}

func (x *GetProcessRequest) GetInspectTimeout() *durationpb.Duration {
	if x != nil {
		return x.InspectTimeout
	}
	return nil
}

type GetProcessResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Process *ProcessInfo           `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Inspect map[string]string      `protobuf:"bytes,2,rep,name=inspect,proto3" json:"inspect,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Why inspect is empty when it was asked for: the process was busy, or
	// exited in the meantime.
	InspectError  string `protobuf:"bytes,3,opt,name=inspect_error,json=inspectError,proto3" json:"inspect_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProcessResponse) Reset() {
	*x = GetProcessResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProcessResponse) ProtoMessage() {}

func (x *GetProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProcessResponse.ProtoReflect.Descriptor instead.
func (*GetProcessResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{17}
}

func (x *GetProcessResponse) GetProcess() *ProcessInfo {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *GetProcessResponse) GetInspect() map[string]string {
	if x != nil {
		return x.Inspect
	}
	return nil
}

func (x *GetProcessResponse) GetInspectError() string {
	if x != nil {
		return x.InspectError
	}
	return ""
}

type SetLogLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Target        *Target                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Level         int32                  `protobuf:"zigzag32,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLogLevelRequest) Reset() {
	*x = SetLogLevelRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLogLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevelRequest) ProtoMessage() {}

func (x *SetLogLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevelRequest.ProtoReflect.Descriptor instead.
func (*SetLogLevelRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{18}
}

func (x *SetLogLevelRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *SetLogLevelRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SetLogLevelRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type SetLogLevelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLogLevelResponse) Reset() {
	*x = SetLogLevelResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLogLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevelResponse) ProtoMessage() {}

func (x *SetLogLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevelResponse.ProtoReflect.Descriptor instead.
func (*SetLogLevelResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{19}
}

type SendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Target        *Target                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Body          *anypb.Any             `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRequest) Reset() {
	*x = SendRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRequest) ProtoMessage() {}

func (x *SendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRequest.ProtoReflect.Descriptor instead.
func (*SendRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{20}
}

func (x *SendRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *SendRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SendRequest) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{21}
}

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Target        *Target                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Body          *anypb.Any             `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{22}
}

func (x *CallRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *CallRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *CallRequest) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

type CallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *anypb.Any             `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallResponse) Reset() {
	*x = CallResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallResponse) ProtoMessage() {}

func (x *CallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallResponse.ProtoReflect.Descriptor instead.
func (*CallResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{23}
}

func (x *CallResponse) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Target        *Target                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Body          *anypb.Any             `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{24}
}

func (x *QueryRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *QueryRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *QueryRequest) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          *anypb.Any             `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{25}
}

func (x *QueryResponse) GetBody() *anypb.Any {
	if x != nil {
		return x.Body
	}
	return nil
}

type ExitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Target        *Target                `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitRequest) Reset() {
	*x = ExitRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitRequest) ProtoMessage() {}

func (x *ExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitRequest.ProtoReflect.Descriptor instead.
func (*ExitRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{26}
}

func (x *ExitRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *ExitRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ExitRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ExitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitResponse) Reset() {
	*x = ExitResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitResponse) ProtoMessage() {}

func (x *ExitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitResponse.ProtoReflect.Descriptor instead.
func (*ExitResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{27}
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Node  string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// Events buffered for this watcher; beyond it events are dropped and
	// counted in Event.missed. Default 256, at most 4096.
	Buffer        uint32 `protobuf:"varint,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{28}
}

func (x *WatchRequest) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WatchRequest) GetBuffer() uint32 {
	if x != nil {
		return x.Buffer
	}
	return 0
}

type WatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{29}
}

func (x *WatchResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Time  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	// Events this watcher lost since the previous one.
	Missed uint64 `protobuf:"varint,2,opt,name=missed,proto3" json:"missed,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_Spawned
	//	*Event_Exited
	//	*Event_LinkUp
	//	*Event_LinkDown
	//	*Event_DeadLetter
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{30}
}

func (x *Event) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Event) GetMissed() uint64 {
	if x != nil {
		return x.Missed
	}
	return 0
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetSpawned() *ProcessInfo {
	if x != nil {
		if x, ok := x.Kind.(*Event_Spawned); ok {
			return x.Spawned
		}
	}
	return nil
}

func (x *Event) GetExited() *Exited {
	if x != nil {
		if x, ok := x.Kind.(*Event_Exited); ok {
			return x.Exited
		}
	}
	return nil
}

func (x *Event) GetLinkUp() *NodeID {
	if x != nil {
		if x, ok := x.Kind.(*Event_LinkUp); ok {
			return x.LinkUp
		}
	}
	return nil
}

func (x *Event) GetLinkDown() *LinkDown {
	if x != nil {
		if x, ok := x.Kind.(*Event_LinkDown); ok {
			return x.LinkDown
		}
	}
	return nil
}

func (x *Event) GetDeadLetter() *DeadLetter {
	if x != nil {
		if x, ok := x.Kind.(*Event_DeadLetter); ok {
			return x.DeadLetter
		}
	}
	return nil
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_Spawned struct {
	Spawned *ProcessInfo `protobuf:"bytes,3,opt,name=spawned,proto3,oneof"`
}

type Event_Exited struct {
	Exited *Exited `protobuf:"bytes,4,opt,name=exited,proto3,oneof"`
}

type Event_LinkUp struct {
	LinkUp *NodeID `protobuf:"bytes,5,opt,name=link_up,json=linkUp,proto3,oneof"`
}

type Event_LinkDown struct {
	LinkDown *LinkDown `protobuf:"bytes,6,opt,name=link_down,json=linkDown,proto3,oneof"`
}

type Event_DeadLetter struct {
	DeadLetter *DeadLetter `protobuf:"bytes,7,opt,name=dead_letter,json=deadLetter,proto3,oneof"`
}

func (*Event_Spawned) isEvent_Kind() {}

func (*Event_Exited) isEvent_Kind() {}

func (*Event_LinkUp) isEvent_Kind() {}

func (*Event_LinkDown) isEvent_Kind() {}

func (*Event_DeadLetter) isEvent_Kind() {}

type Exited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Process       *ProcessInfo           `protobuf:"bytes,1,opt,name=process,proto3" json:"process,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exited) Reset() {
	*x = Exited{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exited) ProtoMessage() {}

func (x *Exited) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exited.ProtoReflect.Descriptor instead.
func (*Exited) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{31}
}

func (x *Exited) GetProcess() *ProcessInfo {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *Exited) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LinkDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *NodeID                `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkDown) Reset() {
	*x = LinkDown{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkDown) ProtoMessage() {}

func (x *LinkDown) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkDown.ProtoReflect.Descriptor instead.
func (*LinkDown) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{32}
}

func (x *LinkDown) GetPeer() *NodeID {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *LinkDown) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeadLetter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	From  *v1.PID                `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To    *v1.PID                `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Proto full name of the message.
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Reason        string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeadLetter) Reset() {
	*x = DeadLetter{}
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetter) ProtoMessage() {}

func (x *DeadLetter) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_inspect_v1_inspect_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetter.ProtoReflect.Descriptor instead.
func (*DeadLetter) Descriptor() ([]byte, []int) {
	return file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP(), []int{33}
}

func (x *DeadLetter) GetFrom() *v1.PID {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DeadLetter) GetTo() *v1.PID {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *DeadLetter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DeadLetter) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_grpcproc_inspect_v1_inspect_proto protoreflect.FileDescriptor

const file_grpcproc_inspect_v1_inspect_proto_rawDesc = "" +
	"\n" +
	"!grpcproc/inspect/v1/inspect.proto\x12\x13grpcproc.inspect.v1\x1a\x1agrpcproc/v1/grpcproc.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\x06NodeID\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vincarnation\x18\x02 \x01(\x04R\vincarnation\"\xcb\x03\n" +
	"\x04Link\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.grpcproc.inspect.v1.NodeIDR\x04peer\x12\x1a\n" +
	"\boutbound\x18\x02 \x01(\bR\boutbound\x124\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1e.grpcproc.inspect.v1.LinkStateR\x05state\x12A\n" +
	"\x0eestablished_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\restablishedAt\x12\x1e\n" +
	"\n" +
	"reconnects\x18\x05 \x01(\x04R\n" +
	"reconnects\x12\x1a\n" +
	"\bmessages\x18\x06 \x01(\x04R\bmessages\x12\x14\n" +
	"\x05bytes\x18\a \x01(\x04R\x05bytes\x12\x1d\n" +
	"\n" +
	"last_error\x18\b \x01(\tR\tlastError\x125\n" +
	"\bretry_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\aretryAt\x12\x16\n" +
	"\x06queued\x18\n" +
	" \x01(\rR\x06queued\x12!\n" +
	"\fqueued_bytes\x18\v \x01(\x04R\vqueuedBytes\x12\x1a\n" +
	"\bsessions\x18\f \x01(\x04R\bsessions\"\xf1\x03\n" +
	"\bNodeInfo\x12+\n" +
	"\x02id\x18\x01 \x01(\v2\x1b.grpcproc.inspect.v1.NodeIDR\x02id\x12\x1c\n" +
	"\tadvertise\x18\x02 \x01(\tR\tadvertise\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x1c\n" +
	"\tprocesses\x18\x04 \x01(\rR\tprocesses\x12\x18\n" +
	"\aspawned\x18\x05 \x01(\x04R\aspawned\x12\x16\n" +
	"\x06exited\x18\x06 \x01(\x04R\x06exited\x12!\n" +
	"\fdead_letters\x18\a \x01(\x04R\vdeadLetters\x12/\n" +
	"\x05links\x18\b \x03(\v2\x19.grpcproc.inspect.v1.LinkR\x05links\x12G\n" +
	"\bmetadata\x18\t \x03(\v2+.grpcproc.inspect.v1.NodeInfo.MetadataEntryR\bmetadata\x125\n" +
	"\amembers\x18\n" +
	" \x03(\v2\x1b.grpcproc.inspect.v1.MemberR\amembers\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x01\n" +
	"\x06Member\x12+\n" +
	"\x02id\x18\x01 \x01(\v2\x1b.grpcproc.inspect.v1.NodeIDR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12E\n" +
	"\bmetadata\x18\x03 \x03(\v2).grpcproc.inspect.v1.Member.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\aMailbox\x12\x14\n" +
	"\x05depth\x18\x01 \x01(\rR\x05depth\x12\x12\n" +
	"\x04peak\x18\x02 \x01(\rR\x04peak\x128\n" +
	"\n" +
	"oldest_age\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\toldestAge\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\rR\x05limit\"\xfc\x04\n" +
	"\vProcessInfo\x12\"\n" +
	"\x03pid\x18\x01 \x01(\v2\x10.grpcproc.v1.PIDR\x03pid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12(\n" +
	"\x06parent\x18\x05 \x01(\v2\x10.grpcproc.v1.PIDR\x06parent\x127\n" +
	"\x05state\x18\x06 \x01(\x0e2!.grpcproc.inspect.v1.ProcessStateR\x05state\x129\n" +
	"\n" +
	"started_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x126\n" +
	"\amailbox\x18\b \x01(\v2\x1c.grpcproc.inspect.v1.MailboxR\amailbox\x12\x1a\n" +
	"\breceived\x18\t \x01(\x04R\breceived\x12\x12\n" +
	"\x04sent\x18\n" +
	" \x01(\x04R\x04sent\x12&\n" +
	"\x0fcalls_in_flight\x18\v \x01(\rR\rcallsInFlight\x12!\n" +
	"\flast_message\x18\f \x01(\tR\vlastMessage\x12\x1a\n" +
	"\bmonitors\x18\r \x01(\rR\bmonitors\x12\x1a\n" +
	"\bwatchers\x18\x0e \x01(\rR\bwatchers\x12\x18\n" +
	"\awakeups\x18\x0f \x01(\x04R\awakeups\x12\x1b\n" +
	"\tlog_level\x18\x10 \x01(\x11R\blogLevel\x12\x14\n" +
	"\x05links\x18\x11 \x01(\rR\x05links\x12\x1b\n" +
	"\ttrap_exit\x18\x12 \x01(\bR\btrapExit\x12\x18\n" +
	"\aglobals\x18\x13 \x03(\tR\aglobals\"L\n" +
	"\x06Target\x12$\n" +
	"\x03pid\x18\x01 \x01(\v2\x10.grpcproc.v1.PIDH\x00R\x03pid\x12\x14\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04nameB\x06\n" +
	"\x04kind\";\n" +
	"\x11LookupNameRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"N\n" +
	"\x12LookupNameResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\"\n" +
	"\x03pid\x18\x02 \x01(\v2\x10.grpcproc.v1.PIDR\x03pid\"T\n" +
	"\x10ListNamesRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x16\n" +
	"\x06prefix\x18\x02 \x01(\tR\x06prefix\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"D\n" +
	"\n" +
	"GlobalName\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\x03pid\x18\x02 \x01(\v2\x10.grpcproc.v1.PIDR\x03pid\"J\n" +
	"\x11ListNamesResponse\x125\n" +
	"\x05names\x18\x01 \x03(\v2\x1f.grpcproc.inspect.v1.GlobalNameR\x05names\"$\n" +
	"\x0eGetNodeRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\"D\n" +
	"\x0fGetNodeResponse\x121\n" +
	"\x04node\x18\x01 \x01(\v2\x1d.grpcproc.inspect.v1.NodeInfoR\x04node\"\xae\x01\n" +
	"\x14ListProcessesRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x127\n" +
	"\x05state\x18\x04 \x01(\x0e2!.grpcproc.inspect.v1.ProcessStateR\x05state\x12\x1f\n" +
	"\vmin_mailbox\x18\x05 \x01(\rR\n" +
	"minMailbox\"W\n" +
	"\x15ListProcessesResponse\x12>\n" +
	"\tprocesses\x18\x01 \x03(\v2 .grpcproc.inspect.v1.ProcessInfoR\tprocesses\"\xba\x01\n" +
	"\x11GetProcessRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.grpcproc.inspect.v1.TargetR\x06target\x12\x18\n" +
	"\ainspect\x18\x03 \x01(\bR\ainspect\x12B\n" +
	"\x0finspect_timeout\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x0einspectTimeout\"\x81\x02\n" +
	"\x12GetProcessResponse\x12:\n" +
	"\aprocess\x18\x01 \x01(\v2 .grpcproc.inspect.v1.ProcessInfoR\aprocess\x12N\n" +
	"\ainspect\x18\x02 \x03(\v24.grpcproc.inspect.v1.GetProcessResponse.InspectEntryR\ainspect\x12#\n" +
	"\rinspect_error\x18\x03 \x01(\tR\finspectError\x1a:\n" +
	"\fInspectEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\x12SetLogLevelRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.grpcproc.inspect.v1.TargetR\x06target\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x11R\x05level\"\x15\n" +
	"\x13SetLogLevelResponse\"\x80\x01\n" +
	"\vSendRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.grpcproc.inspect.v1.TargetR\x06target\x12(\n" +
	"\x04body\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04body\"\x0e\n" +
	"\fSendResponse\"\x80\x01\n" +
	"\vCallRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.grpcproc.inspect.v1.TargetR\x06target\x12(\n" +
	"\x04body\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04body\"8\n" +
	"\fCallResponse\x12(\n" +
	"\x04body\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x04body\"\x81\x01\n" +
	"\fQueryRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.grpcproc.inspect.v1.TargetR\x06target\x12(\n" +
	"\x04body\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\x04body\"9\n" +
	"\rQueryResponse\x12(\n" +
	"\x04body\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x04body\"n\n" +
	"\vExitRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x123\n" +
	"\x06target\x18\x02 \x01(\v2\x1b.grpcproc.inspect.v1.TargetR\x06target\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x0e\n" +
	"\fExitResponse\":\n" +
	"\fWatchRequest\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x16\n" +
	"\x06buffer\x18\x02 \x01(\rR\x06buffer\"A\n" +
	"\rWatchResponse\x120\n" +
	"\x05event\x18\x01 \x01(\v2\x1a.grpcproc.inspect.v1.EventR\x05event\"\x86\x03\n" +
	"\x05Event\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x16\n" +
	"\x06missed\x18\x02 \x01(\x04R\x06missed\x12<\n" +
	"\aspawned\x18\x03 \x01(\v2 .grpcproc.inspect.v1.ProcessInfoH\x00R\aspawned\x125\n" +
	"\x06exited\x18\x04 \x01(\v2\x1b.grpcproc.inspect.v1.ExitedH\x00R\x06exited\x126\n" +
	"\alink_up\x18\x05 \x01(\v2\x1b.grpcproc.inspect.v1.NodeIDH\x00R\x06linkUp\x12<\n" +
	"\tlink_down\x18\x06 \x01(\v2\x1d.grpcproc.inspect.v1.LinkDownH\x00R\blinkDown\x12B\n" +
	"\vdead_letter\x18\a \x01(\v2\x1f.grpcproc.inspect.v1.DeadLetterH\x00R\n" +
	"deadLetterB\x06\n" +
	"\x04kind\"\\\n" +
	"\x06Exited\x12:\n" +
	"\aprocess\x18\x01 \x01(\v2 .grpcproc.inspect.v1.ProcessInfoR\aprocess\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"Q\n" +
	"\bLinkDown\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.grpcproc.inspect.v1.NodeIDR\x04peer\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x80\x01\n" +
	"\n" +
	"DeadLetter\x12$\n" +
	"\x04from\x18\x01 \x01(\v2\x10.grpcproc.v1.PIDR\x04from\x12 \n" +
	"\x02to\x18\x02 \x01(\v2\x10.grpcproc.v1.PIDR\x02to\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason*j\n" +
	"\tLinkState\x12\x1a\n" +
	"\x16LINK_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LINK_STATE_CONNECTING\x10\x01\x12\x11\n" +
	"\rLINK_STATE_UP\x10\x02\x12\x13\n" +
	"\x0fLINK_STATE_DOWN\x10\x03*\x9c\x01\n" +
	"\fProcessState\x12\x1d\n" +
	"\x19PROCESS_STATE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PROCESS_STATE_IDLE\x10\x01\x12\x19\n" +
	"\x15PROCESS_STATE_RUNNING\x10\x02\x12\x1f\n" +
	"\x1bPROCESS_STATE_WAITING_REPLY\x10\x03\x12\x19\n" +
	"\x15PROCESS_STATE_EXITING\x10\x042\xce\a\n" +
	"\tInspector\x12T\n" +
	"\aGetNode\x12#.grpcproc.inspect.v1.GetNodeRequest\x1a$.grpcproc.inspect.v1.GetNodeResponse\x12f\n" +
	"\rListProcesses\x12).grpcproc.inspect.v1.ListProcessesRequest\x1a*.grpcproc.inspect.v1.ListProcessesResponse\x12]\n" +
	"\n" +
	"GetProcess\x12&.grpcproc.inspect.v1.GetProcessRequest\x1a'.grpcproc.inspect.v1.GetProcessResponse\x12`\n" +
	"\vSetLogLevel\x12'.grpcproc.inspect.v1.SetLogLevelRequest\x1a(.grpcproc.inspect.v1.SetLogLevelResponse\x12K\n" +
	"\x04Send\x12 .grpcproc.inspect.v1.SendRequest\x1a!.grpcproc.inspect.v1.SendResponse\x12K\n" +
	"\x04Call\x12 .grpcproc.inspect.v1.CallRequest\x1a!.grpcproc.inspect.v1.CallResponse\x12N\n" +
	"\x05Query\x12!.grpcproc.inspect.v1.QueryRequest\x1a\".grpcproc.inspect.v1.QueryResponse\x12K\n" +
	"\x04Exit\x12 .grpcproc.inspect.v1.ExitRequest\x1a!.grpcproc.inspect.v1.ExitResponse\x12P\n" +
	"\x05Watch\x12!.grpcproc.inspect.v1.WatchRequest\x1a\".grpcproc.inspect.v1.WatchResponse0\x01\x12]\n" +
	"\n" +
	"LookupName\x12&.grpcproc.inspect.v1.LookupNameRequest\x1a'.grpcproc.inspect.v1.LookupNameResponse\x12Z\n" +
	"\tListNames\x12%.grpcproc.inspect.v1.ListNamesRequest\x1a&.grpcproc.inspect.v1.ListNamesResponseBCZAgithub.com/floatdrop/grpcproc/proto/grpcproc/inspect/v1;inspectv1b\x06proto3"

var (
	file_grpcproc_inspect_v1_inspect_proto_rawDescOnce sync.Once
	file_grpcproc_inspect_v1_inspect_proto_rawDescData []byte
)

func file_grpcproc_inspect_v1_inspect_proto_rawDescGZIP() []byte {
	file_grpcproc_inspect_v1_inspect_proto_rawDescOnce.Do(func() {
		file_grpcproc_inspect_v1_inspect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproc_inspect_v1_inspect_proto_rawDesc), len(file_grpcproc_inspect_v1_inspect_proto_rawDesc)))
	})
	return file_grpcproc_inspect_v1_inspect_proto_rawDescData
}

var file_grpcproc_inspect_v1_inspect_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpcproc_inspect_v1_inspect_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_grpcproc_inspect_v1_inspect_proto_goTypes = []any{
	(LinkState)(0),                // 0: grpcproc.inspect.v1.LinkState
	(ProcessState)(0),             // 1: grpcproc.inspect.v1.ProcessState
	(*NodeID)(nil),                // 2: grpcproc.inspect.v1.NodeID
	(*Link)(nil),                  // 3: grpcproc.inspect.v1.Link
	(*NodeInfo)(nil),              // 4: grpcproc.inspect.v1.NodeInfo
	(*Member)(nil),                // 5: grpcproc.inspect.v1.Member
	(*Mailbox)(nil),               // 6: grpcproc.inspect.v1.Mailbox
	(*ProcessInfo)(nil),           // 7: grpcproc.inspect.v1.ProcessInfo
	(*Target)(nil),                // 8: grpcproc.inspect.v1.Target
	(*LookupNameRequest)(nil),     // 9: grpcproc.inspect.v1.LookupNameRequest
	(*LookupNameResponse)(nil),    // 10: grpcproc.inspect.v1.LookupNameResponse
	(*ListNamesRequest)(nil),      // 11: grpcproc.inspect.v1.ListNamesRequest
	(*GlobalName)(nil),            // 12: grpcproc.inspect.v1.GlobalName
	(*ListNamesResponse)(nil),     // 13: grpcproc.inspect.v1.ListNamesResponse
	(*GetNodeRequest)(nil),        // 14: grpcproc.inspect.v1.GetNodeRequest
	(*GetNodeResponse)(nil),       // 15: grpcproc.inspect.v1.GetNodeResponse
	(*ListProcessesRequest)(nil),  // 16: grpcproc.inspect.v1.ListProcessesRequest
	(*ListProcessesResponse)(nil), // 17: grpcproc.inspect.v1.ListProcessesResponse
	(*GetProcessRequest)(nil),     // 18: grpcproc.inspect.v1.GetProcessRequest
	(*GetProcessResponse)(nil),    // 19: grpcproc.inspect.v1.GetProcessResponse
	(*SetLogLevelRequest)(nil),    // 20: grpcproc.inspect.v1.SetLogLevelRequest
	(*SetLogLevelResponse)(nil),   // 21: grpcproc.inspect.v1.SetLogLevelResponse
	(*SendRequest)(nil),           // 22: grpcproc.inspect.v1.SendRequest
	(*SendResponse)(nil),          // 23: grpcproc.inspect.v1.SendResponse
	(*CallRequest)(nil),           // 24: grpcproc.inspect.v1.CallRequest
	(*CallResponse)(nil),          // 25: grpcproc.inspect.v1.CallResponse
	(*QueryRequest)(nil),          // 26: grpcproc.inspect.v1.QueryRequest
	(*QueryResponse)(nil),         // 27: grpcproc.inspect.v1.QueryResponse
	(*ExitRequest)(nil),           // 28: grpcproc.inspect.v1.ExitRequest
	(*ExitResponse)(nil),          // 29: grpcproc.inspect.v1.ExitResponse
	(*WatchRequest)(nil),          // 30: grpcproc.inspect.v1.WatchRequest
	(*WatchResponse)(nil),         // 31: grpcproc.inspect.v1.WatchResponse
	(*Event)(nil),                 // 32: grpcproc.inspect.v1.Event
	(*Exited)(nil),                // 33: grpcproc.inspect.v1.Exited
	(*LinkDown)(nil),              // 34: grpcproc.inspect.v1.LinkDown
	(*DeadLetter)(nil),            // 35: grpcproc.inspect.v1.DeadLetter
	nil,                           // 36: grpcproc.inspect.v1.NodeInfo.MetadataEntry
	nil,                           // 37: grpcproc.inspect.v1.Member.MetadataEntry
	nil,                           // 38: grpcproc.inspect.v1.GetProcessResponse.InspectEntry
	(*timestamppb.Timestamp)(nil), // 39: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 40: google.protobuf.Duration
	(*v1.PID)(nil),                // 41: grpcproc.v1.PID
	(*anypb.Any)(nil),             // 42: google.protobuf.Any
}
var file_grpcproc_inspect_v1_inspect_proto_depIdxs = []int32{
	2,  // 0: grpcproc.inspect.v1.Link.peer:type_name -> grpcproc.inspect.v1.NodeID
	0,  // 1: grpcproc.inspect.v1.Link.state:type_name -> grpcproc.inspect.v1.LinkState
	39, // 2: grpcproc.inspect.v1.Link.established_at:type_name -> google.protobuf.Timestamp
	39, // 3: grpcproc.inspect.v1.Link.retry_at:type_name -> google.protobuf.Timestamp
	2,  // 4: grpcproc.inspect.v1.NodeInfo.id:type_name -> grpcproc.inspect.v1.NodeID
	39, // 5: grpcproc.inspect.v1.NodeInfo.started_at:type_name -> google.protobuf.Timestamp
	3,  // 6: grpcproc.inspect.v1.NodeInfo.links:type_name -> grpcproc.inspect.v1.Link
	36, // 7: grpcproc.inspect.v1.NodeInfo.metadata:type_name -> grpcproc.inspect.v1.NodeInfo.MetadataEntry
	5,  // 8: grpcproc.inspect.v1.NodeInfo.members:type_name -> grpcproc.inspect.v1.Member
	2,  // 9: grpcproc.inspect.v1.Member.id:type_name -> grpcproc.inspect.v1.NodeID
	37, // 10: grpcproc.inspect.v1.Member.metadata:type_name -> grpcproc.inspect.v1.Member.MetadataEntry
	40, // 11: grpcproc.inspect.v1.Mailbox.oldest_age:type_name -> google.protobuf.Duration
	41, // 12: grpcproc.inspect.v1.ProcessInfo.pid:type_name -> grpcproc.v1.PID
	41, // 13: grpcproc.inspect.v1.ProcessInfo.parent:type_name -> grpcproc.v1.PID
	1,  // 14: grpcproc.inspect.v1.ProcessInfo.state:type_name -> grpcproc.inspect.v1.ProcessState
	39, // 15: grpcproc.inspect.v1.ProcessInfo.started_at:type_name -> google.protobuf.Timestamp
	6,  // 16: grpcproc.inspect.v1.ProcessInfo.mailbox:type_name -> grpcproc.inspect.v1.Mailbox
	41, // 17: grpcproc.inspect.v1.Target.pid:type_name -> grpcproc.v1.PID
	41, // 18: grpcproc.inspect.v1.LookupNameResponse.pid:type_name -> grpcproc.v1.PID
	41, // 19: grpcproc.inspect.v1.GlobalName.pid:type_name -> grpcproc.v1.PID
	12, // 20: grpcproc.inspect.v1.ListNamesResponse.names:type_name -> grpcproc.inspect.v1.GlobalName
	4,  // 21: grpcproc.inspect.v1.GetNodeResponse.node:type_name -> grpcproc.inspect.v1.NodeInfo
	1,  // 22: grpcproc.inspect.v1.ListProcessesRequest.state:type_name -> grpcproc.inspect.v1.ProcessState
	7,  // 23: grpcproc.inspect.v1.ListProcessesResponse.processes:type_name -> grpcproc.inspect.v1.ProcessInfo
	8,  // 24: grpcproc.inspect.v1.GetProcessRequest.target:type_name -> grpcproc.inspect.v1.Target
	40, // 25: grpcproc.inspect.v1.GetProcessRequest.inspect_timeout:type_name -> google.protobuf.Duration
	7,  // 26: grpcproc.inspect.v1.GetProcessResponse.process:type_name -> grpcproc.inspect.v1.ProcessInfo
	38, // 27: grpcproc.inspect.v1.GetProcessResponse.inspect:type_name -> grpcproc.inspect.v1.GetProcessResponse.InspectEntry
	8,  // 28: grpcproc.inspect.v1.SetLogLevelRequest.target:type_name -> grpcproc.inspect.v1.Target
	8,  // 29: grpcproc.inspect.v1.SendRequest.target:type_name -> grpcproc.inspect.v1.Target
	42, // 30: grpcproc.inspect.v1.SendRequest.body:type_name -> google.protobuf.Any
	8,  // 31: grpcproc.inspect.v1.CallRequest.target:type_name -> grpcproc.inspect.v1.Target
	42, // 32: grpcproc.inspect.v1.CallRequest.body:type_name -> google.protobuf.Any
	42, // 33: grpcproc.inspect.v1.CallResponse.body:type_name -> google.protobuf.Any
	8,  // 34: grpcproc.inspect.v1.QueryRequest.target:type_name -> grpcproc.inspect.v1.Target
	42, // 35: grpcproc.inspect.v1.QueryRequest.body:type_name -> google.protobuf.Any
	42, // 36: grpcproc.inspect.v1.QueryResponse.body:type_name -> google.protobuf.Any
	8,  // 37: grpcproc.inspect.v1.ExitRequest.target:type_name -> grpcproc.inspect.v1.Target
	32, // 38: grpcproc.inspect.v1.WatchResponse.event:type_name -> grpcproc.inspect.v1.Event
	39, // 39: grpcproc.inspect.v1.Event.time:type_name -> google.protobuf.Timestamp
	7,  // 40: grpcproc.inspect.v1.Event.spawned:type_name -> grpcproc.inspect.v1.ProcessInfo
	33, // 41: grpcproc.inspect.v1.Event.exited:type_name -> grpcproc.inspect.v1.Exited
	2,  // 42: grpcproc.inspect.v1.Event.link_up:type_name -> grpcproc.inspect.v1.NodeID
	34, // 43: grpcproc.inspect.v1.Event.link_down:type_name -> grpcproc.inspect.v1.LinkDown
	35, // 44: grpcproc.inspect.v1.Event.dead_letter:type_name -> grpcproc.inspect.v1.DeadLetter
	7,  // 45: grpcproc.inspect.v1.Exited.process:type_name -> grpcproc.inspect.v1.ProcessInfo
	2,  // 46: grpcproc.inspect.v1.LinkDown.peer:type_name -> grpcproc.inspect.v1.NodeID
	41, // 47: grpcproc.inspect.v1.DeadLetter.from:type_name -> grpcproc.v1.PID
	41, // 48: grpcproc.inspect.v1.DeadLetter.to:type_name -> grpcproc.v1.PID
	14, // 49: grpcproc.inspect.v1.Inspector.GetNode:input_type -> grpcproc.inspect.v1.GetNodeRequest
	16, // 50: grpcproc.inspect.v1.Inspector.ListProcesses:input_type -> grpcproc.inspect.v1.ListProcessesRequest
	18, // 51: grpcproc.inspect.v1.Inspector.GetProcess:input_type -> grpcproc.inspect.v1.GetProcessRequest
	20, // 52: grpcproc.inspect.v1.Inspector.SetLogLevel:input_type -> grpcproc.inspect.v1.SetLogLevelRequest
	22, // 53: grpcproc.inspect.v1.Inspector.Send:input_type -> grpcproc.inspect.v1.SendRequest
	24, // 54: grpcproc.inspect.v1.Inspector.Call:input_type -> grpcproc.inspect.v1.CallRequest
	26, // 55: grpcproc.inspect.v1.Inspector.Query:input_type -> grpcproc.inspect.v1.QueryRequest
	28, // 56: grpcproc.inspect.v1.Inspector.Exit:input_type -> grpcproc.inspect.v1.ExitRequest
	30, // 57: grpcproc.inspect.v1.Inspector.Watch:input_type -> grpcproc.inspect.v1.WatchRequest
	9,  // 58: grpcproc.inspect.v1.Inspector.LookupName:input_type -> grpcproc.inspect.v1.LookupNameRequest
	11, // 59: grpcproc.inspect.v1.Inspector.ListNames:input_type -> grpcproc.inspect.v1.ListNamesRequest
	15, // 60: grpcproc.inspect.v1.Inspector.GetNode:output_type -> grpcproc.inspect.v1.GetNodeResponse
	17, // 61: grpcproc.inspect.v1.Inspector.ListProcesses:output_type -> grpcproc.inspect.v1.ListProcessesResponse
	19, // 62: grpcproc.inspect.v1.Inspector.GetProcess:output_type -> grpcproc.inspect.v1.GetProcessResponse
	21, // 63: grpcproc.inspect.v1.Inspector.SetLogLevel:output_type -> grpcproc.inspect.v1.SetLogLevelResponse
	23, // 64: grpcproc.inspect.v1.Inspector.Send:output_type -> grpcproc.inspect.v1.SendResponse
	25, // 65: grpcproc.inspect.v1.Inspector.Call:output_type -> grpcproc.inspect.v1.CallResponse
	27, // 66: grpcproc.inspect.v1.Inspector.Query:output_type -> grpcproc.inspect.v1.QueryResponse
	29, // 67: grpcproc.inspect.v1.Inspector.Exit:output_type -> grpcproc.inspect.v1.ExitResponse
	31, // 68: grpcproc.inspect.v1.Inspector.Watch:output_type -> grpcproc.inspect.v1.WatchResponse
	10, // 69: grpcproc.inspect.v1.Inspector.LookupName:output_type -> grpcproc.inspect.v1.LookupNameResponse
	13, // 70: grpcproc.inspect.v1.Inspector.ListNames:output_type -> grpcproc.inspect.v1.ListNamesResponse
	60, // [60:71] is the sub-list for method output_type
	49, // [49:60] is the sub-list for method input_type
	49, // [49:49] is the sub-list for extension type_name
	49, // [49:49] is the sub-list for extension extendee
	0,  // [0:49] is the sub-list for field type_name
}

func init() { file_grpcproc_inspect_v1_inspect_proto_init() }
func file_grpcproc_inspect_v1_inspect_proto_init() {
	if File_grpcproc_inspect_v1_inspect_proto != nil {
		return
	}
	file_grpcproc_inspect_v1_inspect_proto_msgTypes[6].OneofWrappers = []any{
		(*Target_Pid)(nil),
		(*Target_Name)(nil),
	}
	file_grpcproc_inspect_v1_inspect_proto_msgTypes[30].OneofWrappers = []any{
		(*Event_Spawned)(nil),
		(*Event_Exited)(nil),
		(*Event_LinkUp)(nil),
		(*Event_LinkDown)(nil),
		(*Event_DeadLetter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproc_inspect_v1_inspect_proto_rawDesc), len(file_grpcproc_inspect_v1_inspect_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcproc_inspect_v1_inspect_proto_goTypes,
		DependencyIndexes: file_grpcproc_inspect_v1_inspect_proto_depIdxs,
		EnumInfos:         file_grpcproc_inspect_v1_inspect_proto_enumTypes,
		MessageInfos:      file_grpcproc_inspect_v1_inspect_proto_msgTypes,
	}.Build()
	File_grpcproc_inspect_v1_inspect_proto = out.File
	file_grpcproc_inspect_v1_inspect_proto_goTypes = nil
	file_grpcproc_inspect_v1_inspect_proto_depIdxs = nil
}
