// grpcproc.inspect.v1 is the inspection surface of a grpcproc node: what
// processes exist, what is in their mailboxes, what each says about itself,
// what is happening on its links. Every tool (CLI, UI, MCP server) is a
// client of this service.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: grpcproc/inspect/v1/inspect.proto

package inspectv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Inspector_GetNode_FullMethodName       = "/grpcproc.inspect.v1.Inspector/GetNode"
	Inspector_ListProcesses_FullMethodName = "/grpcproc.inspect.v1.Inspector/ListProcesses"
	Inspector_GetProcess_FullMethodName    = "/grpcproc.inspect.v1.Inspector/GetProcess"
	Inspector_SetLogLevel_FullMethodName   = "/grpcproc.inspect.v1.Inspector/SetLogLevel"
	Inspector_Send_FullMethodName          = "/grpcproc.inspect.v1.Inspector/Send"
	Inspector_Call_FullMethodName          = "/grpcproc.inspect.v1.Inspector/Call"
	Inspector_Query_FullMethodName         = "/grpcproc.inspect.v1.Inspector/Query"
	Inspector_Exit_FullMethodName          = "/grpcproc.inspect.v1.Inspector/Exit"
	Inspector_Watch_FullMethodName         = "/grpcproc.inspect.v1.Inspector/Watch"
	Inspector_LookupName_FullMethodName    = "/grpcproc.inspect.v1.Inspector/LookupName"
	Inspector_ListNames_FullMethodName     = "/grpcproc.inspect.v1.Inspector/ListNames"
)

// InspectorClient is the client API for Inspector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Inspector is registered by the application next to grpcproc.v1.Node.
//
// Every request names the node it is about. An empty node, or this node's
// own name, is answered here; any other name is forwarded to that node's
// Inspector when the server was built to reach other nodes, so one endpoint
// can inspect the whole cluster.
type InspectorClient interface {
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error)
	// GetProcess returns a snapshot and, if asked, what the process publishes
	// about itself (WithInspect), produced on its own goroutine.
	GetProcess(ctx context.Context, in *GetProcessRequest, opts ...grpc.CallOption) (*GetProcessResponse, error)
	SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error)
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	// Call calls a process and returns its answer, as Node.CallTo does from
	// the node: the request's deadline is the call's. An answer that is an
	// error is Unknown, with the error's text.
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error)
	// Query asks a process a question through the function it was spawned
	// with (grpcproc.WithQuery), as Node.Query does, and returns the answer;
	// an answer that is an error is Unknown, with its text. It changes
	// nothing, so a read-only Inspector allows it. A process spawned with no
	// such function is Unimplemented.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	Exit(ctx context.Context, in *ExitRequest, opts ...grpc.CallOption) (*ExitResponse, error)
	// Watch streams events until the client cancels.
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error)
	// LookupName says who holds a global name, as the node's copy of the
	// names has it. FailedPrecondition for a node without Config.Names.
	LookupName(ctx context.Context, in *LookupNameRequest, opts ...grpc.CallOption) (*LookupNameResponse, error)
	// ListNames lists global names by prefix. FailedPrecondition for a node
	// without Config.Names, Unimplemented for one whose Names cannot list.
	ListNames(ctx context.Context, in *ListNamesRequest, opts ...grpc.CallOption) (*ListNamesResponse, error)
}

type inspectorClient struct {
	cc grpc.ClientConnInterface
}

func NewInspectorClient(cc grpc.ClientConnInterface) InspectorClient {
	return &inspectorClient{cc}
}

func (c *inspectorClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, Inspector_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectorClient) ListProcesses(ctx context.Context, in *ListProcessesRequest, opts ...grpc.CallOption) (*ListProcessesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProcessesResponse)
	err := c.cc.Invoke(ctx, Inspector_ListProcesses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectorClient) GetProcess(ctx context.Context, in *GetProcessRequest, opts ...grpc.CallOption) (*GetProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProcessResponse)
	err := c.cc.Invoke(ctx, Inspector_GetProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectorClient) SetLogLevel(ctx context.Context, in *SetLogLevelRequest, opts ...grpc.CallOption) (*SetLogLevelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLogLevelResponse)
	err := c.cc.Invoke(ctx, Inspector_SetLogLevel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectorClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, Inspector_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectorClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (*CallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallResponse)
	err := c.cc.Invoke(ctx, Inspector_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectorClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, Inspector_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectorClient) Exit(ctx context.Context, in *ExitRequest, opts ...grpc.CallOption) (*ExitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExitResponse)
	err := c.cc.Invoke(ctx, Inspector_Exit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectorClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Inspector_ServiceDesc.Streams[0], Inspector_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, WatchResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Inspector_WatchClient = grpc.ServerStreamingClient[WatchResponse]

func (c *inspectorClient) LookupName(ctx context.Context, in *LookupNameRequest, opts ...grpc.CallOption) (*LookupNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupNameResponse)
	err := c.cc.Invoke(ctx, Inspector_LookupName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inspectorClient) ListNames(ctx context.Context, in *ListNamesRequest, opts ...grpc.CallOption) (*ListNamesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamesResponse)
	err := c.cc.Invoke(ctx, Inspector_ListNames_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InspectorServer is the server API for Inspector service.
// All implementations must embed UnimplementedInspectorServer
// for forward compatibility.
//
// Inspector is registered by the application next to grpcproc.v1.Node.
//
// Every request names the node it is about. An empty node, or this node's
// own name, is answered here; any other name is forwarded to that node's
// Inspector when the server was built to reach other nodes, so one endpoint
// can inspect the whole cluster.
type InspectorServer interface {
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error)
	// GetProcess returns a snapshot and, if asked, what the process publishes
	// about itself (WithInspect), produced on its own goroutine.
	GetProcess(context.Context, *GetProcessRequest) (*GetProcessResponse, error)
	SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error)
	Send(context.Context, *SendRequest) (*SendResponse, error)
	// Call calls a process and returns its answer, as Node.CallTo does from
	// the node: the request's deadline is the call's. An answer that is an
	// error is Unknown, with the error's text.
	Call(context.Context, *CallRequest) (*CallResponse, error)
	// Query asks a process a question through the function it was spawned
	// with (grpcproc.WithQuery), as Node.Query does, and returns the answer;
	// an answer that is an error is Unknown, with its text. It changes
	// nothing, so a read-only Inspector allows it. A process spawned with no
	// such function is Unimplemented.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	Exit(context.Context, *ExitRequest) (*ExitResponse, error)
	// Watch streams events until the client cancels.
	Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error
	// LookupName says who holds a global name, as the node's copy of the
	// names has it. FailedPrecondition for a node without Config.Names.
	LookupName(context.Context, *LookupNameRequest) (*LookupNameResponse, error)
	// ListNames lists global names by prefix. FailedPrecondition for a node
	// without Config.Names, Unimplemented for one whose Names cannot list.
	ListNames(context.Context, *ListNamesRequest) (*ListNamesResponse, error)
	mustEmbedUnimplementedInspectorServer()
}

// UnimplementedInspectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInspectorServer struct{}

func (UnimplementedInspectorServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedInspectorServer) ListProcesses(context.Context, *ListProcessesRequest) (*ListProcessesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProcesses not implemented")
}
func (UnimplementedInspectorServer) GetProcess(context.Context, *GetProcessRequest) (*GetProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProcess not implemented")
}
func (UnimplementedInspectorServer) SetLogLevel(context.Context, *SetLogLevelRequest) (*SetLogLevelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLogLevel not implemented")
}
func (UnimplementedInspectorServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedInspectorServer) Call(context.Context, *CallRequest) (*CallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedInspectorServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedInspectorServer) Exit(context.Context, *ExitRequest) (*ExitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Exit not implemented")
}
func (UnimplementedInspectorServer) Watch(*WatchRequest, grpc.ServerStreamingServer[WatchResponse]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedInspectorServer) LookupName(context.Context, *LookupNameRequest) (*LookupNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupName not implemented")
}
func (UnimplementedInspectorServer) ListNames(context.Context, *ListNamesRequest) (*ListNamesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNames not implemented")
}
func (UnimplementedInspectorServer) mustEmbedUnimplementedInspectorServer() {}
func (UnimplementedInspectorServer) testEmbeddedByValue()                   {}

// UnsafeInspectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InspectorServer will
// result in compilation errors.
type UnsafeInspectorServer interface {
	mustEmbedUnimplementedInspectorServer()
}

func RegisterInspectorServer(s grpc.ServiceRegistrar, srv InspectorServer) {
	// If the following call panics, it indicates UnimplementedInspectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Inspector_ServiceDesc, srv)
}

func _Inspector_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inspector_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inspector_ListProcesses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProcessesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServer).ListProcesses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inspector_ListProcesses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServer).ListProcesses(ctx, req.(*ListProcessesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inspector_GetProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServer).GetProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inspector_GetProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServer).GetProcess(ctx, req.(*GetProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inspector_SetLogLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLogLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServer).SetLogLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inspector_SetLogLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServer).SetLogLevel(ctx, req.(*SetLogLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inspector_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inspector_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inspector_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inspector_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServer).Call(ctx, req.(*CallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inspector_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inspector_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inspector_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inspector_Exit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServer).Exit(ctx, req.(*ExitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inspector_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InspectorServer).Watch(m, &grpc.GenericServerStream[WatchRequest, WatchResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Inspector_WatchServer = grpc.ServerStreamingServer[WatchResponse]

func _Inspector_LookupName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServer).LookupName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inspector_LookupName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServer).LookupName(ctx, req.(*LookupNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Inspector_ListNames_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InspectorServer).ListNames(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Inspector_ListNames_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InspectorServer).ListNames(ctx, req.(*ListNamesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Inspector_ServiceDesc is the grpc.ServiceDesc for Inspector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Inspector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcproc.inspect.v1.Inspector",
	HandlerType: (*InspectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNode",
			Handler:    _Inspector_GetNode_Handler,
		},
		{
			MethodName: "ListProcesses",
			Handler:    _Inspector_ListProcesses_Handler,
		},
		{
			MethodName: "GetProcess",
			Handler:    _Inspector_GetProcess_Handler,
		},
		{
			MethodName: "SetLogLevel",
			Handler:    _Inspector_SetLogLevel_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Inspector_Send_Handler,
		},
		{
			MethodName: "Call",
			Handler:    _Inspector_Call_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Inspector_Query_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _Inspector_Exit_Handler,
		},
		{
			MethodName: "LookupName",
			Handler:    _Inspector_LookupName_Handler,
		},
		{
			MethodName: "ListNames",
			Handler:    _Inspector_ListNames_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Inspector_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "grpcproc/inspect/v1/inspect.proto",
}
