// The conversations service's contract: what a conversation's process
// accepts, what it publishes, and how one is opened. Another service depends
// on this package, never on the service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: guide/proto/conversations/v1/conversations.proto

package conversationsv1

import (
	v1 "github.com/floatdrop/grpcproc/examples/guide/proto/tools/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Open is what the conversations supervisor starts a conversation from.
type Open struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Open) Reset() {
	*x = Open{}
	mi := &file_guide_proto_conversations_v1_conversations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open) ProtoMessage() {}

func (x *Open) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_conversations_v1_conversations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open.ProtoReflect.Descriptor instead.
func (*Open) Descriptor() ([]byte, []int) {
	return file_guide_proto_conversations_v1_conversations_proto_rawDescGZIP(), []int{0}
}

func (x *Open) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request is everything a conversation's process accepts.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Request_Say
	Op            isRequest_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_guide_proto_conversations_v1_conversations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_conversations_v1_conversations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_guide_proto_conversations_v1_conversations_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetOp() isRequest_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Request) GetSay() *Say {
	if x != nil {
		if x, ok := x.Op.(*Request_Say); ok {
			return x.Say
		}
	}
	return nil
}

type isRequest_Op interface {
	isRequest_Op()
}

type Request_Say struct {
	// A call, answered with Said.
	Say *Say `protobuf:"bytes,1,opt,name=say,proto3,oneof"`
}

func (*Request_Say) isRequest_Op() {}

// Say is what the user said. It is answered as its turn begins; the answer
// itself is published, as it comes, on the conversation's topic.
type Say struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Say) Reset() {
	*x = Say{}
	mi := &file_guide_proto_conversations_v1_conversations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Say) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Say) ProtoMessage() {}

func (x *Say) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_conversations_v1_conversations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Say.ProtoReflect.Descriptor instead.
func (*Say) Descriptor() ([]byte, []int) {
	return file_guide_proto_conversations_v1_conversations_proto_rawDescGZIP(), []int{2}
}

func (x *Say) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Said struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Which turn of the conversation this is, from 1.
	Turn          uint64 `protobuf:"varint,1,opt,name=turn,proto3" json:"turn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Said) Reset() {
	*x = Said{}
	mi := &file_guide_proto_conversations_v1_conversations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Said) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Said) ProtoMessage() {}

func (x *Said) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_conversations_v1_conversations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Said.ProtoReflect.Descriptor instead.
func (*Said) Descriptor() ([]byte, []int) {
	return file_guide_proto_conversations_v1_conversations_proto_rawDescGZIP(), []int{3}
}

func (x *Said) GetTurn() uint64 {
	if x != nil {
		return x.Turn
	}
	return 0
}

// Event is what a conversation publishes on its topic.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Turn  uint64                 `protobuf:"varint,1,opt,name=turn,proto3" json:"turn,omitempty"`
	// Which try at an answer a token belongs to, or a retrying begins: see
	// models.v1.Generate.
	Attempt uint64 `protobuf:"varint,9,opt,name=attempt,proto3" json:"attempt,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_Said
	//	*Event_Token
	//	*Event_Tool
	//	*Event_Ran
	//	*Event_Retrying
	//	*Event_Done
	//	*Event_Failed
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_guide_proto_conversations_v1_conversations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_conversations_v1_conversations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_guide_proto_conversations_v1_conversations_proto_rawDescGZIP(), []int{4}
}

func (x *Event) GetTurn() uint64 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *Event) GetAttempt() uint64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetSaid() string {
	if x != nil {
		if x, ok := x.Kind.(*Event_Said); ok {
			return x.Said
		}
	}
	return ""
}

func (x *Event) GetToken() string {
	if x != nil {
		if x, ok := x.Kind.(*Event_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *Event) GetTool() *v1.Run {
	if x != nil {
		if x, ok := x.Kind.(*Event_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *Event) GetRan() *v1.Ran {
	if x != nil {
		if x, ok := x.Kind.(*Event_Ran); ok {
			return x.Ran
		}
	}
	return nil
}

func (x *Event) GetRetrying() string {
	if x != nil {
		if x, ok := x.Kind.(*Event_Retrying); ok {
			return x.Retrying
		}
	}
	return ""
}

func (x *Event) GetDone() bool {
	if x != nil {
		if x, ok := x.Kind.(*Event_Done); ok {
			return x.Done
		}
	}
	return false
}

func (x *Event) GetFailed() string {
	if x != nil {
		if x, ok := x.Kind.(*Event_Failed); ok {
			return x.Failed
		}
	}
	return ""
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_Said struct {
	// What the user said: the turn begins.
	Said string `protobuf:"bytes,8,opt,name=said,proto3,oneof"`
}

type Event_Token struct {
	// The next piece of what the assistant says.
	Token string `protobuf:"bytes,2,opt,name=token,proto3,oneof"`
}

type Event_Tool struct {
	// The model asked for a tool, which is now called.
	Tool *v1.Run `protobuf:"bytes,3,opt,name=tool,proto3,oneof"`
}

type Event_Ran struct {
	// What the tool answered.
	Ran *v1.Ran `protobuf:"bytes,4,opt,name=ran,proto3,oneof"`
}

type Event_Retrying struct {
	// The answer starts over, and why: the node generating it was lost.
	Retrying string `protobuf:"bytes,5,opt,name=retrying,proto3,oneof"`
}

type Event_Done struct {
	// The turn is over.
	Done bool `protobuf:"varint,6,opt,name=done,proto3,oneof"`
}

type Event_Failed struct {
	// The turn failed, and why.
	Failed string `protobuf:"bytes,7,opt,name=failed,proto3,oneof"`
}

func (*Event_Said) isEvent_Kind() {}

func (*Event_Token) isEvent_Kind() {}

func (*Event_Tool) isEvent_Kind() {}

func (*Event_Ran) isEvent_Kind() {}

func (*Event_Retrying) isEvent_Kind() {}

func (*Event_Done) isEvent_Kind() {}

func (*Event_Failed) isEvent_Kind() {}

var File_guide_proto_conversations_v1_conversations_proto protoreflect.FileDescriptor

const file_guide_proto_conversations_v1_conversations_proto_rawDesc = "" +
	"\n" +
	"0guide/proto/conversations/v1/conversations.proto\x12\x10conversations.v1\x1a guide/proto/tools/v1/tools.proto\"\x16\n" +
	"\x04Open\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\aRequest\x12)\n" +
	"\x03say\x18\x01 \x01(\v2\x15.conversations.v1.SayH\x00R\x03sayB\x04\n" +
	"\x02op\"\x19\n" +
	"\x03Say\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x1a\n" +
	"\x04Said\x12\x12\n" +
	"\x04turn\x18\x01 \x01(\x04R\x04turn\"\x81\x02\n" +
	"\x05Event\x12\x12\n" +
	"\x04turn\x18\x01 \x01(\x04R\x04turn\x12\x18\n" +
	"\aattempt\x18\t \x01(\x04R\aattempt\x12\x14\n" +
	"\x04said\x18\b \x01(\tH\x00R\x04said\x12\x16\n" +
	"\x05token\x18\x02 \x01(\tH\x00R\x05token\x12#\n" +
	"\x04tool\x18\x03 \x01(\v2\r.tools.v1.RunH\x00R\x04tool\x12!\n" +
	"\x03ran\x18\x04 \x01(\v2\r.tools.v1.RanH\x00R\x03ran\x12\x1c\n" +
	"\bretrying\x18\x05 \x01(\tH\x00R\bretrying\x12\x14\n" +
	"\x04done\x18\x06 \x01(\bH\x00R\x04done\x12\x18\n" +
	"\x06failed\x18\a \x01(\tH\x00R\x06failedB\x06\n" +
	"\x04kindBUZSgithub.com/floatdrop/grpcproc/examples/guide/proto/conversations/v1;conversationsv1b\x06proto3"

var (
	file_guide_proto_conversations_v1_conversations_proto_rawDescOnce sync.Once
	file_guide_proto_conversations_v1_conversations_proto_rawDescData []byte
)

func file_guide_proto_conversations_v1_conversations_proto_rawDescGZIP() []byte {
	file_guide_proto_conversations_v1_conversations_proto_rawDescOnce.Do(func() {
		file_guide_proto_conversations_v1_conversations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guide_proto_conversations_v1_conversations_proto_rawDesc), len(file_guide_proto_conversations_v1_conversations_proto_rawDesc)))
	})
	return file_guide_proto_conversations_v1_conversations_proto_rawDescData
}

var file_guide_proto_conversations_v1_conversations_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_guide_proto_conversations_v1_conversations_proto_goTypes = []any{
	(*Open)(nil),    // 0: conversations.v1.Open
	(*Request)(nil), // 1: conversations.v1.Request
	(*Say)(nil),     // 2: conversations.v1.Say
	(*Said)(nil),    // 3: conversations.v1.Said
	(*Event)(nil),   // 4: conversations.v1.Event
	(*v1.Run)(nil),  // 5: tools.v1.Run
	(*v1.Ran)(nil),  // 6: tools.v1.Ran
}
var file_guide_proto_conversations_v1_conversations_proto_depIdxs = []int32{
	2, // 0: conversations.v1.Request.say:type_name -> conversations.v1.Say
	5, // 1: conversations.v1.Event.tool:type_name -> tools.v1.Run
	6, // 2: conversations.v1.Event.ran:type_name -> tools.v1.Ran
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_guide_proto_conversations_v1_conversations_proto_init() }
func file_guide_proto_conversations_v1_conversations_proto_init() {
	if File_guide_proto_conversations_v1_conversations_proto != nil {
		return
	}
	file_guide_proto_conversations_v1_conversations_proto_msgTypes[1].OneofWrappers = []any{
		(*Request_Say)(nil),
	}
	file_guide_proto_conversations_v1_conversations_proto_msgTypes[4].OneofWrappers = []any{
		(*Event_Said)(nil),
		(*Event_Token)(nil),
		(*Event_Tool)(nil),
		(*Event_Ran)(nil),
		(*Event_Retrying)(nil),
		(*Event_Done)(nil),
		(*Event_Failed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guide_proto_conversations_v1_conversations_proto_rawDesc), len(file_guide_proto_conversations_v1_conversations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guide_proto_conversations_v1_conversations_proto_goTypes,
		DependencyIndexes: file_guide_proto_conversations_v1_conversations_proto_depIdxs,
		MessageInfos:      file_guide_proto_conversations_v1_conversations_proto_msgTypes,
	}.Build()
	File_guide_proto_conversations_v1_conversations_proto = out.File
	file_guide_proto_conversations_v1_conversations_proto_goTypes = nil
	file_guide_proto_conversations_v1_conversations_proto_depIdxs = nil
}
