// grpcproc.saga.v1 is what a saga engine is asked about the runs in its
// store, through the Inspector: queries, which read, and controls, which
// change a run.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grpcproc/saga/v1/saga.proto

package sagav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_DONE        Status = 2
	Status_STATUS_STUCK       Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_DONE",
		3: "STATUS_STUCK",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_DONE":        2,
		"STATUS_STUCK":       3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcproc_saga_v1_saga_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_grpcproc_saga_v1_saga_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_grpcproc_saga_v1_saga_proto_rawDescGZIP(), []int{0}
}

// Query is the body of an Inspector Query to an engine.
type Query struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Query_List
	//	*Query_Get
	Op            isQuery_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_grpcproc_saga_v1_saga_proto_rawDescGZIP(), []int{0}
}

func (x *Query) GetOp() isQuery_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Query) GetList() *ListRuns {
	if x != nil {
		if x, ok := x.Op.(*Query_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *Query) GetGet() *RunRef {
	if x != nil {
		if x, ok := x.Op.(*Query_Get); ok {
			return x.Get
		}
	}
	return nil
}

type isQuery_Op interface {
	isQuery_Op()
}

type Query_List struct {
	// Answered with Runs.
	List *ListRuns `protobuf:"bytes,1,opt,name=list,proto3,oneof"`
}

type Query_Get struct {
	// Answered with Run, with its data and its signals' payloads as JSON
	// when the engine shows them.
	Get *RunRef `protobuf:"bytes,2,opt,name=get,proto3,oneof"`
}

func (*Query_List) isQuery_Op() {}

func (*Query_Get) isQuery_Op() {}

// Control is the body of an Inspector Call to an engine. Every op is
// answered with google.protobuf.Empty or an error.
type Control struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Control_Resume
	Op            isControl_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_grpcproc_saga_v1_saga_proto_rawDescGZIP(), []int{1}
}

func (x *Control) GetOp() isControl_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Control) GetResume() *RunRef {
	if x != nil {
		if x, ok := x.Op.(*Control_Resume); ok {
			return x.Resume
		}
	}
	return nil
}

type isControl_Op interface {
	isControl_Op()
}

type Control_Resume struct {
	// Makes a Stuck run Active, due at once, its attempts counted from
	// none, as Definition.Resume does.
	Resume *RunRef `protobuf:"bytes,1,opt,name=resume,proto3,oneof"`
}

func (*Control_Resume) isControl_Op() {}

// ListRuns asks for the runs of saga, which the engine must run, or, with
// none named, of every saga it runs, by saga and then ID, after the run after names. A page
// ends at its limit or at two megabytes, and more says so.
type ListRuns struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Saga  string                 `protobuf:"bytes,1,opt,name=saga,proto3" json:"saga,omitempty"`
	// The statuses to list; all of them when there is none.
	Status []Status `protobuf:"varint,2,rep,packed,name=status,proto3,enum=grpcproc.saga.v1.Status" json:"status,omitempty"`
	// How many to answer with: 100 when 0, at most 1000.
	Limit uint32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// The run to list after, as the last of a previous answer.
	After         *RunRef `protobuf:"bytes,4,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuns) Reset() {
	*x = ListRuns{}
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuns) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuns) ProtoMessage() {}

func (x *ListRuns) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuns.ProtoReflect.Descriptor instead.
func (*ListRuns) Descriptor() ([]byte, []int) {
	return file_grpcproc_saga_v1_saga_proto_rawDescGZIP(), []int{2}
}

func (x *ListRuns) GetSaga() string {
	if x != nil {
		return x.Saga
	}
	return ""
}

func (x *ListRuns) GetStatus() []Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListRuns) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRuns) GetAfter() *RunRef {
	if x != nil {
		return x.After
	}
	return nil
}

type RunRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Saga          string                 `protobuf:"bytes,1,opt,name=saga,proto3" json:"saga,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRef) Reset() {
	*x = RunRef{}
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRef) ProtoMessage() {}

func (x *RunRef) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRef.ProtoReflect.Descriptor instead.
func (*RunRef) Descriptor() ([]byte, []int) {
	return file_grpcproc_saga_v1_saga_proto_rawDescGZIP(), []int{3}
}

func (x *RunRef) GetSaga() string {
	if x != nil {
		return x.Saga
	}
	return ""
}

func (x *RunRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Runs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Runs  []*Run                 `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	// Set when there are more after the last.
	More          bool `protobuf:"varint,2,opt,name=more,proto3" json:"more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runs) Reset() {
	*x = Runs{}
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runs) ProtoMessage() {}

func (x *Runs) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runs.ProtoReflect.Descriptor instead.
func (*Runs) Descriptor() ([]byte, []int) {
	return file_grpcproc_saga_v1_saga_proto_rawDescGZIP(), []int{4}
}

func (x *Runs) GetRuns() []*Run {
	if x != nil {
		return x.Runs
	}
	return nil
}

func (x *Runs) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

// Run is a run as its store keeps it. A run in a list has neither its data
// nor its signals, only how many wait, and a kilobyte of its error and
// cause.
type Run struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Saga        string                 `protobuf:"bytes,1,opt,name=saga,proto3" json:"saga,omitempty"`
	Id          string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	SagaVersion uint64                 `protobuf:"varint,3,opt,name=saga_version,json=sagaVersion,proto3" json:"saga_version,omitempty"`
	State       string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Status      Status                 `protobuf:"varint,5,opt,name=status,proto3,enum=grpcproc.saga.v1.Status" json:"status,omitempty"`
	// The run's data, as JSON, when the engine shows data
	// (saga.Config.InspectData): empty, with data_omitted 0, when it does not.
	Data string `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// The size of the data, encoded or as JSON, when it is over a megabyte,
	// too much to carry: data is then empty.
	DataOmitted uint64 `protobuf:"varint,23,opt,name=data_omitted,json=dataOmitted,proto3" json:"data_omitted,omitempty"`
	// How many signals wait, in a list.
	Waiting       uint32                 `protobuf:"varint,24,opt,name=waiting,proto3" json:"waiting,omitempty"`
	Visit         uint64                 `protobuf:"varint,7,opt,name=visit,proto3" json:"visit,omitempty"`
	EffectDone    bool                   `protobuf:"varint,8,opt,name=effect_done,json=effectDone,proto3" json:"effect_done,omitempty"`
	Attempts      int64                  `protobuf:"varint,9,opt,name=attempts,proto3" json:"attempts,omitempty"`
	Error         string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	Cause         string                 `protobuf:"bytes,11,opt,name=cause,proto3" json:"cause,omitempty"`
	Wake          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=wake,proto3" json:"wake,omitempty"`
	RetryAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=retry_at,json=retryAt,proto3" json:"retry_at,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=deadline,proto3" json:"deadline,omitempty"`
	Owner         string                 `protobuf:"bytes,15,opt,name=owner,proto3" json:"owner,omitempty"`
	LeaseUntil    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=lease_until,json=leaseUntil,proto3" json:"lease_until,omitempty"`
	Epoch         uint64                 `protobuf:"varint,17,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Seen          uint64                 `protobuf:"varint,18,opt,name=seen,proto3" json:"seen,omitempty"`
	Inbox         []*Signal              `protobuf:"bytes,19,rep,name=inbox,proto3" json:"inbox,omitempty"`
	Revision      uint64                 `protobuf:"varint,20,opt,name=revision,proto3" json:"revision,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Run) Reset() {
	*x = Run{}
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Run) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Run) ProtoMessage() {}

func (x *Run) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Run.ProtoReflect.Descriptor instead.
func (*Run) Descriptor() ([]byte, []int) {
	return file_grpcproc_saga_v1_saga_proto_rawDescGZIP(), []int{5}
}

func (x *Run) GetSaga() string {
	if x != nil {
		return x.Saga
	}
	return ""
}

func (x *Run) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Run) GetSagaVersion() uint64 {
	if x != nil {
		return x.SagaVersion
	}
	return 0
}

func (x *Run) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Run) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Run) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Run) GetDataOmitted() uint64 {
	if x != nil {
		return x.DataOmitted
	}
	return 0
}

func (x *Run) GetWaiting() uint32 {
	if x != nil {
		return x.Waiting
	}
	return 0
}

func (x *Run) GetVisit() uint64 {
	if x != nil {
		return x.Visit
	}
	return 0
}

func (x *Run) GetEffectDone() bool {
	if x != nil {
		return x.EffectDone
	}
	return false
}

func (x *Run) GetAttempts() int64 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *Run) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Run) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *Run) GetWake() *timestamppb.Timestamp {
	if x != nil {
		return x.Wake
	}
	return nil
}

func (x *Run) GetRetryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RetryAt
	}
	return nil
}

func (x *Run) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *Run) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Run) GetLeaseUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseUntil
	}
	return nil
}

func (x *Run) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Run) GetSeen() uint64 {
	if x != nil {
		return x.Seen
	}
	return 0
}

func (x *Run) GetInbox() []*Signal {
	if x != nil {
		return x.Inbox
	}
	return nil
}

func (x *Run) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *Run) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Run) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Signal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Event string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	// Its payload, as JSON, when the engine shows data and the saga accepts
	// the event.
	Payload string `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Version uint64 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	// The size of the payload, encoded or as JSON, when it is over sixteen
	// kilobytes: payload is then empty.
	PayloadOmitted uint64 `protobuf:"varint,5,opt,name=payload_omitted,json=payloadOmitted,proto3" json:"payload_omitted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_saga_v1_saga_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_grpcproc_saga_v1_saga_proto_rawDescGZIP(), []int{6}
}

func (x *Signal) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Signal) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *Signal) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Signal) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Signal) GetPayloadOmitted() uint64 {
	if x != nil {
		return x.PayloadOmitted
	}
	return 0
}

var File_grpcproc_saga_v1_saga_proto protoreflect.FileDescriptor

const file_grpcproc_saga_v1_saga_proto_rawDesc = "" +
	"\n" +
	"\x1bgrpcproc/saga/v1/saga.proto\x12\x10grpcproc.saga.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"m\n" +
	"\x05Query\x120\n" +
	"\x04list\x18\x01 \x01(\v2\x1a.grpcproc.saga.v1.ListRunsH\x00R\x04list\x12,\n" +
	"\x03get\x18\x02 \x01(\v2\x18.grpcproc.saga.v1.RunRefH\x00R\x03getB\x04\n" +
	"\x02op\"C\n" +
	"\aControl\x122\n" +
	"\x06resume\x18\x01 \x01(\v2\x18.grpcproc.saga.v1.RunRefH\x00R\x06resumeB\x04\n" +
	"\x02op\"\x96\x01\n" +
	"\bListRuns\x12\x12\n" +
	"\x04saga\x18\x01 \x01(\tR\x04saga\x120\n" +
	"\x06status\x18\x02 \x03(\x0e2\x18.grpcproc.saga.v1.StatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12.\n" +
	"\x05after\x18\x04 \x01(\v2\x18.grpcproc.saga.v1.RunRefR\x05after\",\n" +
	"\x06RunRef\x12\x12\n" +
	"\x04saga\x18\x01 \x01(\tR\x04saga\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"E\n" +
	"\x04Runs\x12)\n" +
	"\x04runs\x18\x01 \x03(\v2\x15.grpcproc.saga.v1.RunR\x04runs\x12\x12\n" +
	"\x04more\x18\x02 \x01(\bR\x04more\"\xc2\x06\n" +
	"\x03Run\x12\x12\n" +
	"\x04saga\x18\x01 \x01(\tR\x04saga\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12!\n" +
	"\fsaga_version\x18\x03 \x01(\x04R\vsagaVersion\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x120\n" +
	"\x06status\x18\x05 \x01(\x0e2\x18.grpcproc.saga.v1.StatusR\x06status\x12\x12\n" +
	"\x04data\x18\x06 \x01(\tR\x04data\x12!\n" +
	"\fdata_omitted\x18\x17 \x01(\x04R\vdataOmitted\x12\x18\n" +
	"\awaiting\x18\x18 \x01(\rR\awaiting\x12\x14\n" +
	"\x05visit\x18\a \x01(\x04R\x05visit\x12\x1f\n" +
	"\veffect_done\x18\b \x01(\bR\n" +
	"effectDone\x12\x1a\n" +
	"\battempts\x18\t \x01(\x03R\battempts\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\x12\x14\n" +
	"\x05cause\x18\v \x01(\tR\x05cause\x12.\n" +
	"\x04wake\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\x04wake\x125\n" +
	"\bretry_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\aretryAt\x126\n" +
	"\bdeadline\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x14\n" +
	"\x05owner\x18\x0f \x01(\tR\x05owner\x12;\n" +
	"\vlease_until\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"leaseUntil\x12\x14\n" +
	"\x05epoch\x18\x11 \x01(\x04R\x05epoch\x12\x12\n" +
	"\x04seen\x18\x12 \x01(\x04R\x04seen\x12.\n" +
	"\x05inbox\x18\x13 \x03(\v2\x18.grpcproc.saga.v1.SignalR\x05inbox\x12\x1a\n" +
	"\brevision\x18\x14 \x01(\x04R\brevision\x129\n" +
	"\n" +
	"created_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8d\x01\n" +
	"\x06Signal\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\x12'\n" +
	"\x0fpayload_omitted\x18\x05 \x01(\x04R\x0epayloadOmitted*V\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x0f\n" +
	"\vSTATUS_DONE\x10\x02\x12\x10\n" +
	"\fSTATUS_STUCK\x10\x03BBZ@github.com/floatdrop/grpcproc/saga/proto/grpcproc/saga/v1;sagav1b\x06proto3"

var (
	file_grpcproc_saga_v1_saga_proto_rawDescOnce sync.Once
	file_grpcproc_saga_v1_saga_proto_rawDescData []byte
)

func file_grpcproc_saga_v1_saga_proto_rawDescGZIP() []byte {
	file_grpcproc_saga_v1_saga_proto_rawDescOnce.Do(func() {
		file_grpcproc_saga_v1_saga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproc_saga_v1_saga_proto_rawDesc), len(file_grpcproc_saga_v1_saga_proto_rawDesc)))
	})
	return file_grpcproc_saga_v1_saga_proto_rawDescData
}

var file_grpcproc_saga_v1_saga_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_grpcproc_saga_v1_saga_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_grpcproc_saga_v1_saga_proto_goTypes = []any{
	(Status)(0),                   // 0: grpcproc.saga.v1.Status
	(*Query)(nil),                 // 1: grpcproc.saga.v1.Query
	(*Control)(nil),               // 2: grpcproc.saga.v1.Control
	(*ListRuns)(nil),              // 3: grpcproc.saga.v1.ListRuns
	(*RunRef)(nil),                // 4: grpcproc.saga.v1.RunRef
	(*Runs)(nil),                  // 5: grpcproc.saga.v1.Runs
	(*Run)(nil),                   // 6: grpcproc.saga.v1.Run
	(*Signal)(nil),                // 7: grpcproc.saga.v1.Signal
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_grpcproc_saga_v1_saga_proto_depIdxs = []int32{
	3,  // 0: grpcproc.saga.v1.Query.list:type_name -> grpcproc.saga.v1.ListRuns
	4,  // 1: grpcproc.saga.v1.Query.get:type_name -> grpcproc.saga.v1.RunRef
	4,  // 2: grpcproc.saga.v1.Control.resume:type_name -> grpcproc.saga.v1.RunRef
	0,  // 3: grpcproc.saga.v1.ListRuns.status:type_name -> grpcproc.saga.v1.Status
	4,  // 4: grpcproc.saga.v1.ListRuns.after:type_name -> grpcproc.saga.v1.RunRef
	6,  // 5: grpcproc.saga.v1.Runs.runs:type_name -> grpcproc.saga.v1.Run
	0,  // 6: grpcproc.saga.v1.Run.status:type_name -> grpcproc.saga.v1.Status
	8,  // 7: grpcproc.saga.v1.Run.wake:type_name -> google.protobuf.Timestamp
	8,  // 8: grpcproc.saga.v1.Run.retry_at:type_name -> google.protobuf.Timestamp
	8,  // 9: grpcproc.saga.v1.Run.deadline:type_name -> google.protobuf.Timestamp
	8,  // 10: grpcproc.saga.v1.Run.lease_until:type_name -> google.protobuf.Timestamp
	7,  // 11: grpcproc.saga.v1.Run.inbox:type_name -> grpcproc.saga.v1.Signal
	8,  // 12: grpcproc.saga.v1.Run.created_at:type_name -> google.protobuf.Timestamp
	8,  // 13: grpcproc.saga.v1.Run.updated_at:type_name -> google.protobuf.Timestamp
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_grpcproc_saga_v1_saga_proto_init() }
func file_grpcproc_saga_v1_saga_proto_init() {
	if File_grpcproc_saga_v1_saga_proto != nil {
		return
	}
	file_grpcproc_saga_v1_saga_proto_msgTypes[0].OneofWrappers = []any{
		(*Query_List)(nil),
		(*Query_Get)(nil),
	}
	file_grpcproc_saga_v1_saga_proto_msgTypes[1].OneofWrappers = []any{
		(*Control_Resume)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproc_saga_v1_saga_proto_rawDesc), len(file_grpcproc_saga_v1_saga_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcproc_saga_v1_saga_proto_goTypes,
		DependencyIndexes: file_grpcproc_saga_v1_saga_proto_depIdxs,
		EnumInfos:         file_grpcproc_saga_v1_saga_proto_enumTypes,
		MessageInfos:      file_grpcproc_saga_v1_saga_proto_msgTypes,
	}.Build()
	File_grpcproc_saga_v1_saga_proto = out.File
	file_grpcproc_saga_v1_saga_proto_goTypes = nil
	file_grpcproc_saga_v1_saga_proto_depIdxs = nil
}
