// grpcproc.v1 is the wire protocol between grpcproc nodes. One stream per
// (sender node -> receiver node) direction carries every interaction between
// the two, in order: messages, calls, replies, monitors and down notifications.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grpcproc/v1/grpcproc.proto

package grpcprocv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_KIND_UNSPECIFIED Kind = 0
	// The first envelope on a stream, sent by the server.
	Kind_KIND_HELLO Kind = 1
	// An asynchronous message.
	Kind_KIND_SEND Kind = 2
	// A request that expects a KIND_REPLY with the same ref.
	Kind_KIND_CALL  Kind = 3
	Kind_KIND_REPLY Kind = 4
	// Asks the target's node to send KIND_DOWN when the target exits.
	Kind_KIND_MONITOR   Kind = 5
	Kind_KIND_DEMONITOR Kind = 6
	// Tells the target that the sender exited.
	Kind_KIND_DOWN Kind = 7
	// Asks the target to terminate.
	Kind_KIND_EXIT Kind = 8
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_HELLO",
		2: "KIND_SEND",
		3: "KIND_CALL",
		4: "KIND_REPLY",
		5: "KIND_MONITOR",
		6: "KIND_DEMONITOR",
		7: "KIND_DOWN",
		8: "KIND_EXIT",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_HELLO":       1,
		"KIND_SEND":        2,
		"KIND_CALL":        3,
		"KIND_REPLY":       4,
		"KIND_MONITOR":     5,
		"KIND_DEMONITOR":   6,
		"KIND_DOWN":        7,
		"KIND_EXIT":        8,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcproc_v1_grpcproc_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_grpcproc_v1_grpcproc_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_grpcproc_v1_grpcproc_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_OK          Status = 1
	// The handler returned an error; reason carries its text.
	Status_STATUS_ERROR Status = 2
	// No such process, or it exited before answering; or, with reason
	// "mailbox full", its mailbox had no room, and the call was never handled.
	Status_STATUS_NOPROC Status = 3
	// The process exists but does not accept this message type.
	Status_STATUS_TYPE Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_ERROR",
		3: "STATUS_NOPROC",
		4: "STATUS_TYPE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_ERROR":       2,
		"STATUS_NOPROC":      3,
		"STATUS_TYPE":        4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpcproc_v1_grpcproc_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_grpcproc_v1_grpcproc_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_grpcproc_v1_grpcproc_proto_rawDescGZIP(), []int{1}
}

// Frame is what a link writes at once: every envelope queued since its last
// write, in order. Under load many envelopes share one gRPC message.
type Frame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelopes     []*Envelope            `protobuf:"bytes,1,rep,name=envelopes,proto3" json:"envelopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_grpcproc_v1_grpcproc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_v1_grpcproc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_grpcproc_v1_grpcproc_proto_rawDescGZIP(), []int{0}
}

func (x *Frame) GetEnvelopes() []*Envelope {
	if x != nil {
		return x.Envelopes
	}
	return nil
}

// PID identifies a process anywhere in the cluster.
type PID struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Node  string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// Incarnation changes every time a node starts, so a PID from before a
	// restart never reaches a process created after it.
	Incarnation   uint64 `protobuf:"varint,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	Id            uint64 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PID) Reset() {
	*x = PID{}
	mi := &file_grpcproc_v1_grpcproc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PID) ProtoMessage() {}

func (x *PID) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_v1_grpcproc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PID.ProtoReflect.Descriptor instead.
func (*PID) Descriptor() ([]byte, []int) {
	return file_grpcproc_v1_grpcproc_proto_rawDescGZIP(), []int{1}
}

func (x *PID) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PID) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *PID) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Envelope is one interaction between two processes. Its processes are
// named by incarnation and id alone: the sender is on the node that opened
// the link, the target on the node that accepted it, so neither node name
// travels with each envelope. It is one flat message so that decoding one
// allocates little.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  Kind                   `protobuf:"varint,1,opt,name=kind,proto3,enum=grpcproc.v1.Kind" json:"kind,omitempty"`
	// The process on the sending node; id 0 is the node itself.
	FromIncarnation uint64 `protobuf:"varint,2,opt,name=from_incarnation,json=fromIncarnation,proto3" json:"from_incarnation,omitempty"`
	FromId          uint64 `protobuf:"varint,3,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	// The process on the receiving node, unless to_name addresses it by name.
	ToIncarnation uint64 `protobuf:"varint,4,opt,name=to_incarnation,json=toIncarnation,proto3" json:"to_incarnation,omitempty"`
	ToId          uint64 `protobuf:"varint,5,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`
	ToName        string `protobuf:"bytes,6,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	// A call's id, echoed by its reply, or a monitor's id, echoed by its down.
	Ref uint64 `protobuf:"varint,7,opt,name=ref,proto3" json:"ref,omitempty"`
	// A reply's status.
	Status Status `protobuf:"varint,8,opt,name=status,proto3,enum=grpcproc.v1.Status" json:"status,omitempty"`
	// A reply's error, or the reason of a down or an exit.
	Reason string `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	// The body of a send, a call or a reply: its message type's full name and
	// its encoding.
	BodyType string `protobuf:"bytes,10,opt,name=body_type,json=bodyType,proto3" json:"body_type,omitempty"`
	Body     []byte `protobuf:"bytes,11,opt,name=body,proto3" json:"body,omitempty"`
	Hello    *Hello `protobuf:"bytes,12,opt,name=hello,proto3" json:"hello,omitempty"`
	// A call's time left, in nanoseconds, when it was written: its caller
	// waits that long for the reply. 0 for a caller with no deadline. A time
	// left rather than a deadline, so that clocks need not agree.
	TimeoutNanos int64 `protobuf:"varint,13,opt,name=timeout_nanos,json=timeoutNanos,proto3" json:"timeout_nanos,omitempty"`
	// Propagated context: trace headers, tenant. Never interpreted by
	// grpcproc itself.
	Metadata map[string]string `protobuf:"bytes,15,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// A call's: its caller watches, monitors or is linked to, the process the
	// callee places the watch on, under the call's ref. The callee places it
	// before it answers: on a process it spawns, before that process runs, or
	// on one that runs. A peer that does not know it places none.
	Watch bool `protobuf:"varint,16,opt,name=watch,proto3" json:"watch,omitempty"`
	// A reply's: the process of the replying node the call's watch was placed
	// on. 0 when none was.
	WatchedId     uint64 `protobuf:"varint,17,opt,name=watched_id,json=watchedId,proto3" json:"watched_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_grpcproc_v1_grpcproc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_v1_grpcproc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_grpcproc_v1_grpcproc_proto_rawDescGZIP(), []int{2}
}

func (x *Envelope) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNSPECIFIED
}

func (x *Envelope) GetFromIncarnation() uint64 {
	if x != nil {
		return x.FromIncarnation
	}
	return 0
}

func (x *Envelope) GetFromId() uint64 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *Envelope) GetToIncarnation() uint64 {
	if x != nil {
		return x.ToIncarnation
	}
	return 0
}

func (x *Envelope) GetToId() uint64 {
	if x != nil {
		return x.ToId
	}
	return 0
}

func (x *Envelope) GetToName() string {
	if x != nil {
		return x.ToName
	}
	return ""
}

func (x *Envelope) GetRef() uint64 {
	if x != nil {
		return x.Ref
	}
	return 0
}

func (x *Envelope) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Envelope) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Envelope) GetBodyType() string {
	if x != nil {
		return x.BodyType
	}
	return ""
}

func (x *Envelope) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		return x.Hello
	}
	return nil
}

func (x *Envelope) GetTimeoutNanos() int64 {
	if x != nil {
		return x.TimeoutNanos
	}
	return 0
}

func (x *Envelope) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Envelope) GetWatch() bool {
	if x != nil {
		return x.Watch
	}
	return false
}

func (x *Envelope) GetWatchedId() uint64 {
	if x != nil {
		return x.WatchedId
	}
	return 0
}

// Hello is the first envelope on a stream, sent by the server. It names the
// node the client actually reached.
type Hello struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Node        string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Incarnation uint64                 `protobuf:"varint,2,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	Version     uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// How many sessions the server's links with the client's node have had
	// end, as the server counts them, the client's count taken if larger. A
	// client that counts fewer learns that the server ended its session with
	// it; one that counts more dialed in a session that has ended since.
	Session       uint64 `protobuf:"varint,4,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_grpcproc_v1_grpcproc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_v1_grpcproc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_grpcproc_v1_grpcproc_proto_rawDescGZIP(), []int{3}
}

func (x *Hello) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Hello) GetIncarnation() uint64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *Hello) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Hello) GetSession() uint64 {
	if x != nil {
		return x.Session
	}
	return 0
}

var File_grpcproc_v1_grpcproc_proto protoreflect.FileDescriptor

const file_grpcproc_v1_grpcproc_proto_rawDesc = "" +
	"\n" +
	"\x1agrpcproc/v1/grpcproc.proto\x12\vgrpcproc.v1\"<\n" +
	"\x05Frame\x123\n" +
	"\tenvelopes\x18\x01 \x03(\v2\x15.grpcproc.v1.EnvelopeR\tenvelopes\"K\n" +
	"\x03PID\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12 \n" +
	"\vincarnation\x18\x02 \x01(\x04R\vincarnation\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x04R\x02id\"\xd4\x04\n" +
	"\bEnvelope\x12%\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x11.grpcproc.v1.KindR\x04kind\x12)\n" +
	"\x10from_incarnation\x18\x02 \x01(\x04R\x0ffromIncarnation\x12\x17\n" +
	"\afrom_id\x18\x03 \x01(\x04R\x06fromId\x12%\n" +
	"\x0eto_incarnation\x18\x04 \x01(\x04R\rtoIncarnation\x12\x13\n" +
	"\x05to_id\x18\x05 \x01(\x04R\x04toId\x12\x17\n" +
	"\ato_name\x18\x06 \x01(\tR\x06toName\x12\x10\n" +
	"\x03ref\x18\a \x01(\x04R\x03ref\x12+\n" +
	"\x06status\x18\b \x01(\x0e2\x13.grpcproc.v1.StatusR\x06status\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\x12\x1b\n" +
	"\tbody_type\x18\n" +
	" \x01(\tR\bbodyType\x12\x12\n" +
	"\x04body\x18\v \x01(\fR\x04body\x12(\n" +
	"\x05hello\x18\f \x01(\v2\x12.grpcproc.v1.HelloR\x05hello\x12#\n" +
	"\rtimeout_nanos\x18\r \x01(\x03R\ftimeoutNanos\x12?\n" +
	"\bmetadata\x18\x0f \x03(\v2#.grpcproc.v1.Envelope.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05watch\x18\x10 \x01(\bR\x05watch\x12\x1d\n" +
	"\n" +
	"watched_id\x18\x11 \x01(\x04R\twatchedId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\x05Hello\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12 \n" +
	"\vincarnation\x18\x02 \x01(\x04R\vincarnation\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12\x18\n" +
	"\asession\x18\x04 \x01(\x04R\asession*\x9e\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"KIND_HELLO\x10\x01\x12\r\n" +
	"\tKIND_SEND\x10\x02\x12\r\n" +
	"\tKIND_CALL\x10\x03\x12\x0e\n" +
	"\n" +
	"KIND_REPLY\x10\x04\x12\x10\n" +
	"\fKIND_MONITOR\x10\x05\x12\x12\n" +
	"\x0eKIND_DEMONITOR\x10\x06\x12\r\n" +
	"\tKIND_DOWN\x10\a\x12\r\n" +
	"\tKIND_EXIT\x10\b*e\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x11\n" +
	"\rSTATUS_NOPROC\x10\x03\x12\x0f\n" +
	"\vSTATUS_TYPE\x10\x042:\n" +
	"\x04Node\x122\n" +
	"\x04Link\x12\x12.grpcproc.v1.Frame\x1a\x12.grpcproc.v1.Frame(\x010\x01B<Z:github.com/floatdrop/grpcproc/proto/grpcproc/v1;grpcprocv1b\x06proto3"

var (
	file_grpcproc_v1_grpcproc_proto_rawDescOnce sync.Once
	file_grpcproc_v1_grpcproc_proto_rawDescData []byte
)

func file_grpcproc_v1_grpcproc_proto_rawDescGZIP() []byte {
	file_grpcproc_v1_grpcproc_proto_rawDescOnce.Do(func() {
		file_grpcproc_v1_grpcproc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproc_v1_grpcproc_proto_rawDesc), len(file_grpcproc_v1_grpcproc_proto_rawDesc)))
	})
	return file_grpcproc_v1_grpcproc_proto_rawDescData
}

var file_grpcproc_v1_grpcproc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpcproc_v1_grpcproc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpcproc_v1_grpcproc_proto_goTypes = []any{
	(Kind)(0),        // 0: grpcproc.v1.Kind
	(Status)(0),      // 1: grpcproc.v1.Status
	(*Frame)(nil),    // 2: grpcproc.v1.Frame
	(*PID)(nil),      // 3: grpcproc.v1.PID
	(*Envelope)(nil), // 4: grpcproc.v1.Envelope
	(*Hello)(nil),    // 5: grpcproc.v1.Hello
	nil,              // 6: grpcproc.v1.Envelope.MetadataEntry
}
var file_grpcproc_v1_grpcproc_proto_depIdxs = []int32{
	4, // 0: grpcproc.v1.Frame.envelopes:type_name -> grpcproc.v1.Envelope
	0, // 1: grpcproc.v1.Envelope.kind:type_name -> grpcproc.v1.Kind
	1, // 2: grpcproc.v1.Envelope.status:type_name -> grpcproc.v1.Status
	5, // 3: grpcproc.v1.Envelope.hello:type_name -> grpcproc.v1.Hello
	6, // 4: grpcproc.v1.Envelope.metadata:type_name -> grpcproc.v1.Envelope.MetadataEntry
	2, // 5: grpcproc.v1.Node.Link:input_type -> grpcproc.v1.Frame
	2, // 6: grpcproc.v1.Node.Link:output_type -> grpcproc.v1.Frame
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_grpcproc_v1_grpcproc_proto_init() }
func file_grpcproc_v1_grpcproc_proto_init() {
	if File_grpcproc_v1_grpcproc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproc_v1_grpcproc_proto_rawDesc), len(file_grpcproc_v1_grpcproc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpcproc_v1_grpcproc_proto_goTypes,
		DependencyIndexes: file_grpcproc_v1_grpcproc_proto_depIdxs,
		EnumInfos:         file_grpcproc_v1_grpcproc_proto_enumTypes,
		MessageInfos:      file_grpcproc_v1_grpcproc_proto_msgTypes,
	}.Build()
	File_grpcproc_v1_grpcproc_proto = out.File
	file_grpcproc_v1_grpcproc_proto_goTypes = nil
	file_grpcproc_v1_grpcproc_proto_depIdxs = nil
}
