// The models service's contract: what a GPU node's scheduler accepts and
// answers. Another service depends on this package, never on the service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: guide/proto/models/v1/models.proto

package modelsv1

import (
	v1 "github.com/floatdrop/grpcproc/examples/guide/proto/tools/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role is who said a turn of a conversation.
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_USER        Role = 1
	Role_ROLE_ASSISTANT   Role = 2
	// What a tool returned for the call the assistant made.
	Role_ROLE_TOOL Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_USER",
		2: "ROLE_ASSISTANT",
		3: "ROLE_TOOL",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_USER":        1,
		"ROLE_ASSISTANT":   2,
		"ROLE_TOOL":        3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_guide_proto_models_v1_models_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_guide_proto_models_v1_models_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_guide_proto_models_v1_models_proto_rawDescGZIP(), []int{0}
}

type Turn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Role  Role                   `protobuf:"varint,1,opt,name=role,proto3,enum=models.v1.Role" json:"role,omitempty"`
	Text  string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	// The tool the assistant asked for, having said text.
	Tool          *v1.Run `protobuf:"bytes,3,opt,name=tool,proto3" json:"tool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Turn) Reset() {
	*x = Turn{}
	mi := &file_guide_proto_models_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Turn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Turn) ProtoMessage() {}

func (x *Turn) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_models_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Turn.ProtoReflect.Descriptor instead.
func (*Turn) Descriptor() ([]byte, []int) {
	return file_guide_proto_models_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Turn) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *Turn) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Turn) GetTool() *v1.Run {
	if x != nil {
		return x.Tool
	}
	return nil
}

// Generate asks for the next thing the assistant says. It is a call,
// answered with Generated once the model is done; the tokens are published
// meanwhile, as they come, on the topic it names.
type Generate struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	History []*Turn                `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	// The topic the tokens go to: its node and its name. Its events are
	// conversations.v1.Event.
	TopicNode string `protobuf:"bytes,2,opt,name=topic_node,json=topicNode,proto3" json:"topic_node,omitempty"`
	Topic     string `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	// The turn of the conversation this answers, set on every token.
	Turn uint64 `protobuf:"varint,4,opt,name=turn,proto3" json:"turn,omitempty"`
	// Which try at the answer this is, larger than any before it, and set on
	// every token: a node that lost its caller may go on publishing after
	// another was asked, and a subscriber drops the tokens of an earlier try.
	Attempt       uint64 `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generate) Reset() {
	*x = Generate{}
	mi := &file_guide_proto_models_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generate) ProtoMessage() {}

func (x *Generate) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_models_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generate.ProtoReflect.Descriptor instead.
func (*Generate) Descriptor() ([]byte, []int) {
	return file_guide_proto_models_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *Generate) GetHistory() []*Turn {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *Generate) GetTopicNode() string {
	if x != nil {
		return x.TopicNode
	}
	return ""
}

func (x *Generate) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Generate) GetTurn() uint64 {
	if x != nil {
		return x.Turn
	}
	return 0
}

func (x *Generate) GetAttempt() uint64 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

// Generated is the scheduler's answer. A node with no slot free says so:
// busy is part of the answer, and an error means the node did not answer.
type Generated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Everything the model said.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// The tool it wants called before it goes on, if any.
	Tool *v1.Run `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	// No slot was free: nothing was generated.
	Busy          bool `protobuf:"varint,3,opt,name=busy,proto3" json:"busy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Generated) Reset() {
	*x = Generated{}
	mi := &file_guide_proto_models_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Generated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Generated) ProtoMessage() {}

func (x *Generated) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_models_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Generated.ProtoReflect.Descriptor instead.
func (*Generated) Descriptor() ([]byte, []int) {
	return file_guide_proto_models_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *Generated) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Generated) GetTool() *v1.Run {
	if x != nil {
		return x.Tool
	}
	return nil
}

func (x *Generated) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

var File_guide_proto_models_v1_models_proto protoreflect.FileDescriptor

const file_guide_proto_models_v1_models_proto_rawDesc = "" +
	"\n" +
	"\"guide/proto/models/v1/models.proto\x12\tmodels.v1\x1a guide/proto/tools/v1/tools.proto\"b\n" +
	"\x04Turn\x12#\n" +
	"\x04role\x18\x01 \x01(\x0e2\x0f.models.v1.RoleR\x04role\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12!\n" +
	"\x04tool\x18\x03 \x01(\v2\r.tools.v1.RunR\x04tool\"\x98\x01\n" +
	"\bGenerate\x12)\n" +
	"\ahistory\x18\x01 \x03(\v2\x0f.models.v1.TurnR\ahistory\x12\x1d\n" +
	"\n" +
	"topic_node\x18\x02 \x01(\tR\ttopicNode\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x12\n" +
	"\x04turn\x18\x04 \x01(\x04R\x04turn\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x04R\aattempt\"V\n" +
	"\tGenerated\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12!\n" +
	"\x04tool\x18\x02 \x01(\v2\r.tools.v1.RunR\x04tool\x12\x12\n" +
	"\x04busy\x18\x03 \x01(\bR\x04busy*N\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tROLE_USER\x10\x01\x12\x12\n" +
	"\x0eROLE_ASSISTANT\x10\x02\x12\r\n" +
	"\tROLE_TOOL\x10\x03BGZEgithub.com/floatdrop/grpcproc/examples/guide/proto/models/v1;modelsv1b\x06proto3"

var (
	file_guide_proto_models_v1_models_proto_rawDescOnce sync.Once
	file_guide_proto_models_v1_models_proto_rawDescData []byte
)

func file_guide_proto_models_v1_models_proto_rawDescGZIP() []byte {
	file_guide_proto_models_v1_models_proto_rawDescOnce.Do(func() {
		file_guide_proto_models_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guide_proto_models_v1_models_proto_rawDesc), len(file_guide_proto_models_v1_models_proto_rawDesc)))
	})
	return file_guide_proto_models_v1_models_proto_rawDescData
}

var file_guide_proto_models_v1_models_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_guide_proto_models_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_guide_proto_models_v1_models_proto_goTypes = []any{
	(Role)(0),         // 0: models.v1.Role
	(*Turn)(nil),      // 1: models.v1.Turn
	(*Generate)(nil),  // 2: models.v1.Generate
	(*Generated)(nil), // 3: models.v1.Generated
	(*v1.Run)(nil),    // 4: tools.v1.Run
}
var file_guide_proto_models_v1_models_proto_depIdxs = []int32{
	0, // 0: models.v1.Turn.role:type_name -> models.v1.Role
	4, // 1: models.v1.Turn.tool:type_name -> tools.v1.Run
	1, // 2: models.v1.Generate.history:type_name -> models.v1.Turn
	4, // 3: models.v1.Generated.tool:type_name -> tools.v1.Run
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_guide_proto_models_v1_models_proto_init() }
func file_guide_proto_models_v1_models_proto_init() {
	if File_guide_proto_models_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guide_proto_models_v1_models_proto_rawDesc), len(file_guide_proto_models_v1_models_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guide_proto_models_v1_models_proto_goTypes,
		DependencyIndexes: file_guide_proto_models_v1_models_proto_depIdxs,
		EnumInfos:         file_guide_proto_models_v1_models_proto_enumTypes,
		MessageInfos:      file_guide_proto_models_v1_models_proto_msgTypes,
	}.Build()
	File_guide_proto_models_v1_models_proto = out.File
	file_guide_proto_models_v1_models_proto_goTypes = nil
	file_guide_proto_models_v1_models_proto_depIdxs = nil
}
